{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.5.0/test-util-coroutine-0.5.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.5.0.jar",
          "url": "test-util-coroutine-jvm-0.5.0.jar",
          "size": 6100,
          "sha512": "06c4b8eac33c7b5032ab3896eefbdee420189f46e266b9cff63e233dd32cdabf982cce04e910537871080d84f0b5715d1226c12efe43918521ce4b5420f99877",
          "sha256": "99d5a65598a545ec241aabfb7637aeadb691c8d45edbd136c5e2b085337b4cca",
          "sha1": "2291f5db720e6085110e6d99d2acea82fe6fcbfd",
          "md5": "3266422522725cfbbf00f92a118b7ceb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.5.0.jar",
          "url": "test-util-coroutine-jvm-0.5.0.jar",
          "size": 6100,
          "sha512": "06c4b8eac33c7b5032ab3896eefbdee420189f46e266b9cff63e233dd32cdabf982cce04e910537871080d84f0b5715d1226c12efe43918521ce4b5420f99877",
          "sha256": "99d5a65598a545ec241aabfb7637aeadb691c8d45edbd136c5e2b085337b4cca",
          "sha1": "2291f5db720e6085110e6d99d2acea82fe6fcbfd",
          "md5": "3266422522725cfbbf00f92a118b7ceb"
        }
      ]
    }
  ]
}
