{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/.1.10.0/fhir-helper-.1.10.0.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": ".1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-.1.10.0.jar",
          "url": "fhir-helper-jvm-.1.10.0.jar",
          "size": 114322,
          "sha512": "629f9c9229d040505e2ba4e0a4b01ca43e1258dc79ea43448cf482e616bc4bb4f2add741d350ba0b189cf85c28a02c4f2c496658d5128b3d0830976ddbd1b1b4",
          "sha256": "586f59cece6f3151169acbbb5a31d92d6b9f2704c8c2900cd966962c650c0fee",
          "sha1": "c9f3073748db73575d01f1c97fa08b8e3780c37e",
          "md5": "213e3786a89b0d1f4727c7320d33b62a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-.1.10.0.jar",
          "url": "fhir-helper-jvm-.1.10.0.jar",
          "size": 114322,
          "sha512": "629f9c9229d040505e2ba4e0a4b01ca43e1258dc79ea43448cf482e616bc4bb4f2add741d350ba0b189cf85c28a02c4f2c496658d5128b3d0830976ddbd1b1b4",
          "sha256": "586f59cece6f3151169acbbb5a31d92d6b9f2704c8c2900cd966962c650c0fee",
          "sha1": "c9f3073748db73575d01f1c97fa08b8e3780c37e",
          "md5": "213e3786a89b0d1f4727c7320d33b62a"
        }
      ]
    }
  ]
}
