{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.14.0.jar",
          "url": "crypto-jvm-1.14.0.jar",
          "size": 57739,
          "sha512": "43065b7869da578072afc4a6b2b6558c2c242f8f8a424097376a85e0eded23d4ee433285d79f96a9b71e7941599cbd6c39cb19d1dc56de6d791efe5bc4e95cf4",
          "sha256": "91020b005dbaeaef1bc69118774f2f9481019c8997fbc79ac80bf3520d1d9928",
          "sha1": "432dcc5eed6a05f92afac70cf38e3057bac53602",
          "md5": "5f5f5717b7ab82cbb45ad02456ab8395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.14.0.jar",
          "url": "crypto-jvm-1.14.0.jar",
          "size": 57739,
          "sha512": "43065b7869da578072afc4a6b2b6558c2c242f8f8a424097376a85e0eded23d4ee433285d79f96a9b71e7941599cbd6c39cb19d1dc56de6d791efe5bc4e95cf4",
          "sha256": "91020b005dbaeaef1bc69118774f2f9481019c8997fbc79ac80bf3520d1d9928",
          "sha1": "432dcc5eed6a05f92afac70cf38e3057bac53602",
          "md5": "5f5f5717b7ab82cbb45ad02456ab8395"
        }
      ]
    }
  ]
}
