{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.14.0.jar",
          "url": "auth-common-1.14.0.jar",
          "size": 3578,
          "sha512": "01d7388a989efb8a9f5ed67306b668571c9da9641f2686f542a99974033784d0371e90e1315b4240d0dd0cfdc451c02ab65ca7613d0fb1d84b03bb0c5db68fb6",
          "sha256": "793ac7a6426a24faa4afe17bed4b3845e7c89ac75d54d46b08569734d48cde56",
          "sha1": "d9fef89fcf875bf5163b68536dd17d85d9990b76",
          "md5": "f8cf64523cc7075721c2897a1a397492"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.14.0.jar",
          "url": "auth-common-1.14.0.jar",
          "size": 3578,
          "sha512": "01d7388a989efb8a9f5ed67306b668571c9da9641f2686f542a99974033784d0371e90e1315b4240d0dd0cfdc451c02ab65ca7613d0fb1d84b03bb0c5db68fb6",
          "sha256": "793ac7a6426a24faa4afe17bed4b3845e7c89ac75d54d46b08569734d48cde56",
          "sha1": "d9fef89fcf875bf5163b68536dd17d85d9990b76",
          "md5": "f8cf64523cc7075721c2897a1a397492"
        }
      ]
    }
  ]
}
