{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.15.0/auth-1.15.0.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auth-jvm-1.15.0.jar",
          "url": "auth-jvm-1.15.0.jar",
          "size": 34774,
          "sha512": "babf0528457f1cf42c94c9f039c1d9964c17a536126eaf9912a3370737f8540f488f5cf3d1abe388c145531f3852d43d96583aa8e499eb2da6203359b183da3a",
          "sha256": "75e38b8447fc938b1b36db109dcdc195ab2f09c799bdc9a0505f0b8ced9ec12b",
          "sha1": "f4a652702627e7d2e07359de20d20552780623f6",
          "md5": "e1a33216be6750328623c94e505a3026"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.15.0.jar",
          "url": "auth-jvm-1.15.0.jar",
          "size": 34774,
          "sha512": "babf0528457f1cf42c94c9f039c1d9964c17a536126eaf9912a3370737f8540f488f5cf3d1abe388c145531f3852d43d96583aa8e499eb2da6203359b183da3a",
          "sha256": "75e38b8447fc938b1b36db109dcdc195ab2f09c799bdc9a0505f0b8ced9ec12b",
          "sha1": "f4a652702627e7d2e07359de20d20552780623f6",
          "md5": "e1a33216be6750328623c94e505a3026"
        }
      ]
    }
  ]
}
