{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.14.0/error-1.14.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.14.0.klib",
          "size": 7092,
          "sha512": "bd0613db2bcda7b4cf0f99630a2518c764b1928ccc62939e7765e388ff55281200b050e0ab975ab740c005772420b50ade6882069ef2d0a5c1b79166ba710f6e",
          "sha256": "907f86960b0b76a972fe76771d1506d917ec0bed02f01d1aab16dbaad1c360cc",
          "sha1": "25a74c3e0b97b8ad7fb8974cf0c9d389fd2ae237",
          "md5": "f8a076466dce6f04d75cbeb50784d893"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.14.0-metadata.jar",
          "url": "error-iosarm64-1.14.0-metadata.jar",
          "size": 5050,
          "sha512": "b1ed52e40d65427feb42a4d1a8c4a60ab3b767141f875e1777a2a77b0354f030c9ebbc20bee1a7d86f2b12ab83577ec1a8f2d142683606d6611dc44a79452aaa",
          "sha256": "16e5b3d7135f99f57fbc42976b36ec552fd571edfa3bd5e9452bc7266395e67b",
          "sha1": "1ff05c7514c1757556e6c690addf996ab7de7f2b",
          "md5": "b976f79e29daeae24d98b0cb8a7aa839"
        }
      ]
    }
  ]
}
