{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4/data-donation-sdk-iosx64-0.0.4.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lgt2zzr3ojfdxbn4yqn3u2a7tm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4.jar",
          "url": "data-donation-sdk-metadata-0.0.4.jar",
          "size": 63773,
          "sha512": "ee805eb3012976098b6051c003ed99670a6a9f75b8d21f3084b090392e1b62b75b88fea71571240003ad5afbed1ef465982256dddcb96454f56178b9c3b8c21a",
          "sha256": "01ef9c76ab024a11d534f393350b63a92cbb06440d19979c99a322931d6027e9",
          "sha1": "a115d3051cea3924c2a18b0c8437012ca57c5679",
          "md5": "0cb22fcd3acabaea692d63e4279a2529"
        }
      ]
    }
  ]
}
