{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3/data-donation-sdk-iosx64-0.0.3.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2kxab4z6gjdxvb5bbsu5q4x4zm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3.jar",
          "url": "data-donation-sdk-metadata-0.0.3.jar",
          "size": 63040,
          "sha512": "c3fd5a4b62f6a9e7e4a33e4738b23d7bda8ffa04a20ac5b1fc139bcbe43590edac6d4d38289f9b5f010e40b2a145aae26a53155fac21955113ed9521c581a74b",
          "sha256": "29dd1761bc66964d662469e6d33498d8686e731ec200d180ae2fcb0b8ca1a928",
          "sha1": "62181fbf51e73f82f1b558c3ae46be6715257708",
          "md5": "b9e8d3307bf3d377038b9f884c3ecdb2"
        }
      ]
    }
  ]
}
