{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.1.0/test-util-coroutine-0.1.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "acivhj2lyrg6hfvetor6vh3due"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.1.0.jar",
          "url": "test-util-coroutine-jvm-0.1.0.jar",
          "size": 5987,
          "sha512": "cd253f8ed2dec5a56b1a677ea4fd30a39114095b65740da33acc9793e93f43f16e8a59ba454ae8bd629fc36a454c73590d7cf9d8aeb674198e98b6ba59c951ba",
          "sha256": "abc8ad2dce893cf978438347e51eb1925e0d5b591a0b4bea0a66c3a2bfe25d3b",
          "sha1": "c0756e0f3d62318cdd2db06486383f43a29d3ace",
          "md5": "ebe1dec3e47c360a45e0185f0aee85c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.1.0.jar",
          "url": "test-util-coroutine-jvm-0.1.0.jar",
          "size": 5987,
          "sha512": "cd253f8ed2dec5a56b1a677ea4fd30a39114095b65740da33acc9793e93f43f16e8a59ba454ae8bd629fc36a454c73590d7cf9d8aeb674198e98b6ba59c951ba",
          "sha256": "abc8ad2dce893cf978438347e51eb1925e0d5b591a0b4bea0a66c3a2bfe25d3b",
          "sha1": "c0756e0f3d62318cdd2db06486383f43a29d3ace",
          "md5": "ebe1dec3e47c360a45e0185f0aee85c5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.1.0/test-util-coroutine-metadata-0.1.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.1.0"
      }
    }
  ]
}
