{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.14.0/securestore-1.14.0.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.14.0.jar",
          "url": "securestore-jvm-1.14.0.jar",
          "size": 16659,
          "sha512": "ae7e892d53a89f5c024ae968e28647cfb39c304c651125796e2524d05bb555f4b1236fa433ca899f8486c62ae8b9f1773c9eda957a9a2be259ca4ce2823e8f46",
          "sha256": "7cf580b48d5e5909bfd4fd3cb45d92d356de4c760ad6509c5ebff964e82cbe29",
          "sha1": "bb6270f6763b08cc8052edc2471298730c61f825",
          "md5": "dfd3a04256241e856ba783780821316b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0.jar",
          "url": "securestore-jvm-1.14.0.jar",
          "size": 16659,
          "sha512": "ae7e892d53a89f5c024ae968e28647cfb39c304c651125796e2524d05bb555f4b1236fa433ca899f8486c62ae8b9f1773c9eda957a9a2be259ca4ce2823e8f46",
          "sha256": "7cf580b48d5e5909bfd4fd3cb45d92d356de4c760ad6509c5ebff964e82cbe29",
          "sha1": "bb6270f6763b08cc8052edc2471298730c61f825",
          "md5": "dfd3a04256241e856ba783780821316b"
        }
      ]
    }
  ]
}
