{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.9.0/util-coroutine-jvm-1.9.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aitrtwsoyvbztl5swknjdi3ioi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.9.0.jar",
          "url": "util-coroutine-metadata-1.9.0.jar",
          "size": 2237,
          "sha512": "4470b53699cae529c795ed399b62fe6648c601fa42fdcf3e16430947f355992ab88924e33fe11e249daffbe72be1b47676ec2f4ca38c9d6f0fcf3733050ce106",
          "sha256": "b7cb28f8849cad3e17e17ae58814cfb23d140f88f75eb6cd62cf8790d7a73427",
          "sha1": "c16d8a33af53e3d4810d55f8ca31b9b5bb2eb00f",
          "md5": "5208e0d279a4ff286ab76159243577df"
        }
      ]
    }
  ]
}
