{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uaqlyonijvbj3jsaxzmoi6suce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "6792a19edb7a2c0a71a282c0328ca7b7978fec735a265617459b256a81aab18e13705d4076e5ca793890f0502169e549f474f8aeefca61adc5b9019465b2c3f9",
          "sha256": "56062e1c71aecb7f1a521a78a0eec7021bd1343a751ef928be289901f7c0901e",
          "sha1": "1e1319b68089ce4eb8c1c15e11ac38e5d9ad3420",
          "md5": "b3c6b514598df2106a347fbada4325d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "6792a19edb7a2c0a71a282c0328ca7b7978fec735a265617459b256a81aab18e13705d4076e5ca793890f0502169e549f474f8aeefca61adc5b9019465b2c3f9",
          "sha256": "56062e1c71aecb7f1a521a78a0eec7021bd1343a751ef928be289901f7c0901e",
          "sha1": "1e1319b68089ce4eb8c1c15e11ac38e5d9ad3420",
          "md5": "b3c6b514598df2106a347fbada4325d6"
        }
      ]
    }
  ]
}
