{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.17.0/auth-1.17.0.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auth-jvm-1.17.0.jar",
          "url": "auth-jvm-1.17.0.jar",
          "size": 34180,
          "sha512": "97ac32b0f0f8bd222c0da44a708a1a26704429bfdac3b6119af93bde0e4c9d1efdad1e6fc45d9d8a85189d331bba909d263305d5c58783a8c4bb5b758294255d",
          "sha256": "be33e07d5b783527250a89f417791f182f067a5e788680f20e3c3ba6a8a0f579",
          "sha1": "8d5a78d08fb8f838f596e82a9cb6658cfb9e8049",
          "md5": "8020790b5b794ab29c1aee084aba5379"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.17.0.jar",
          "url": "auth-jvm-1.17.0.jar",
          "size": 34180,
          "sha512": "97ac32b0f0f8bd222c0da44a708a1a26704429bfdac3b6119af93bde0e4c9d1efdad1e6fc45d9d8a85189d331bba909d263305d5c58783a8c4bb5b758294255d",
          "sha256": "be33e07d5b783527250a89f417791f182f067a5e788680f20e3c3ba6a8a0f579",
          "sha1": "8d5a78d08fb8f838f596e82a9cb6658cfb9e8049",
          "md5": "8020790b5b794ab29c1aee084aba5379"
        }
      ]
    }
  ]
}
