{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-metadata-0.2.0-all.jar",
          "url": "objc-util-0.2.0-all.jar",
          "size": 706,
          "sha512": "6efcdf1efa69546775b5bfba5f4724c673493253db824ab01f3e1d5dcd677cbf2c2c475c1e359b9d3d440262291ff3864eb0c0d2b851b845e8bff2f108ebb797",
          "sha256": "9454baf50a205be3be0e8f11faed025c42a7b074161f5deb4fcc473bd37df84e",
          "sha1": "918ed66807743660b3f8107d921445c2a4eacecd",
          "md5": "24a2d5c95a4b23597a93dbf3bb30ce00"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "objc-util-0.2.0.jar",
          "url": "objc-util-0.2.0.jar",
          "size": 261,
          "sha512": "c84c1c2e4a5df7999f62d39dfe28aa32c783b84a9213a697d361244640d82e39946075c99b878ad874fc459cbbcb528afb13e46c43aabb193898f7ae9a5be08a",
          "sha256": "d3dbed5ba3ff2f127e63bec0f25e23bd56fc1636b844cbb8c980f94605e649cc",
          "sha1": "d0756cac8596aa19c29390a914305c51bf7f6383",
          "md5": "ef9a7721cb0713735076038e3779ae60"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosarm64/0.2.0/objc-util-iosarm64-0.2.0.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosarm64/0.2.0/objc-util-iosarm64-0.2.0.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosx64/0.2.0/objc-util-iosx64-0.2.0.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosx64/0.2.0/objc-util-iosx64-0.2.0.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosx64",
        "version": "0.2.0"
      }
    }
  ]
}
