{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor-jvm/0.1.0/test-util-ktor-jvm-0.1.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor-jvm",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "acivhj2lyrg6hfvetor6vh3due"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-0.1.0.jar",
          "url": "test-util-ktor-metadata-0.1.0.jar",
          "size": 3186,
          "sha512": "3f854c3402efbc75170fc9f23a62a99129c76385d050a92427039076aa45d0860c89ac04648d797998b8d7b0c53ea75fa2bf0b4928334c1b2e798e3c32535c85",
          "sha256": "079a022b759d830c34de991772e3ad34a3d9cc39d982ee3d8ad0edcfd8978e49",
          "sha1": "82885ded95cc264933cd92194aaee1faa340121b",
          "md5": "3c76aacccd95557b1393ec3acebbf31f"
        }
      ]
    }
  ]
}
