{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.16.0/crypto-1.16.0.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.16.0.jar",
          "url": "crypto-jvm-1.16.0.jar",
          "size": 58650,
          "sha512": "6ea31f95cba99e459e418e03b9a24788bca198f2eabd1a7e3a04d9ea9a962b3bfbefe7923d7354ae4ae55ba1c3061cb2bc29df47124a6070142a8defab06369c",
          "sha256": "685433785b0eaa9b56705634983a0b1f1238abbd6b5e4cc5979000d866cd65c2",
          "sha1": "b7e8902833ba4aea38e82d0b53c40b9f61f1f751",
          "md5": "4ee0a135f115a2f472c56e4b76b2b41f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.16.0.jar",
          "url": "crypto-jvm-1.16.0.jar",
          "size": 58650,
          "sha512": "6ea31f95cba99e459e418e03b9a24788bca198f2eabd1a7e3a04d9ea9a962b3bfbefe7923d7354ae4ae55ba1c3061cb2bc29df47124a6070142a8defab06369c",
          "sha256": "685433785b0eaa9b56705634983a0b1f1238abbd6b5e4cc5979000d866cd65c2",
          "sha1": "b7e8902833ba4aea38e82d0b53c40b9f61f1f751",
          "md5": "4ee0a135f115a2f472c56e4b76b2b41f"
        }
      ]
    }
  ]
}
