{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.4.0/test-util-ktor-0.4.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.4.0.klib",
          "size": 15755,
          "sha512": "880d4cae6db0c73abca2ca2b38a7ba33a96d508adf205c8394e575fe0f7bd942cb4bdd4b573095778575f3c293b8a3d6f9facd4bf899e2f4fef48294ab20d31f",
          "sha256": "3b0f9dd9a65f38ed7f262eb03ec1a5af57d6abffdd5a9e871cbe4d3a284f07c0",
          "sha1": "00cd4a5ba77d94690846a40e9aa0deafb1fed1c5",
          "md5": "37037efa20d56d7bf04d7d5d2d16eebb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.4.0-metadata.jar",
          "url": "test-util-ktor-iosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "bfdb6ca3f251ce70633f38d04d9b4cb4641fd2d276c01881ee8971075bb8a4d833c6f954b4ac33717e984955b1e03409b9ce8674b915cb930aebeba34a52f98e",
          "sha256": "3e89bb8d8efe89e8c3e2ee3ba37b8c0aa0ed23dd8a1149e19adf5e11133e0e82",
          "sha1": "c9720913c1336d72114edfff5de773a57f7fafc2",
          "md5": "f03b4fc99c363728e1405eb0cb4725dc"
        }
      ]
    }
  ]
}
