{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.16.0/auth-1.16.0.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auth-jvm-1.16.0.jar",
          "url": "auth-jvm-1.16.0.jar",
          "size": 34248,
          "sha512": "980620ce71b3bb0e941982211b19600a64862a1aac9f1a76883a08e45db144ba802411928a807be8373416121a9b038aefa1fdbeaa4887c086467ef0c5d3f0aa",
          "sha256": "d555b1bf7de0409b3d66a6e0b5791602a8b86df90397c2187ef2c7fdc0b7f933",
          "sha1": "edc37addc01bde584484917b891fe29ad67ce6de",
          "md5": "4a1494a4b02abc74cc65d705b92b24f5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.16.0.jar",
          "url": "auth-jvm-1.16.0.jar",
          "size": 34248,
          "sha512": "980620ce71b3bb0e941982211b19600a64862a1aac9f1a76883a08e45db144ba802411928a807be8373416121a9b038aefa1fdbeaa4887c086467ef0c5d3f0aa",
          "sha256": "d555b1bf7de0409b3d66a6e0b5791602a8b86df90397c2187ef2c7fdc0b7f933",
          "sha1": "edc37addc01bde584484917b891fe29ad67ce6de",
          "md5": "4a1494a4b02abc74cc65d705b92b24f5"
        }
      ]
    }
  ]
}
