{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.1/data-donation-sdk-iosx64-0.1.1.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "guq27ugwg5firf2zf75jzwccpq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.1.jar",
          "url": "data-donation-sdk-metadata-0.1.1.jar",
          "size": 39250,
          "sha512": "7a74e4db31f1ed18d98ccf06258eda540c8ed96f7b6c1ec6ee2117567142047f5892c2fe19a3302adecd1a011c27855d4b3a0d70b56b119ed4e7cbb2f72c26d0",
          "sha256": "4da98ca04e97a00e64e764058e2d15390cdc8733b72a3194ca0248d818f14163",
          "sha1": "e1e0742f67d30d9953caffa3a700aae505511192",
          "md5": "724d6efc43dc3ee6622c298241b8fe1d"
        }
      ]
    }
  ]
}
