{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uaqlyonijvbj3jsaxzmoi6suce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6fee3f2fa2de4c2878cc7bdaf79244976bae1ceaa02cef3dab8b581cbb011f9515f6b78c9e2ba54cce0a49c90f7df39bc52a82f54c33cefe4047f69f385c4606",
          "sha256": "9816bcaeb4433dfb7c9735b6e032b14213220942b8f82fdad82312a5ecea843f",
          "sha1": "6c79ce7fe797a08b5cee4f4f4af8dc91aaba2bd7",
          "md5": "81eeaea3f6f21573ea4859b628aecb20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6fee3f2fa2de4c2878cc7bdaf79244976bae1ceaa02cef3dab8b581cbb011f9515f6b78c9e2ba54cce0a49c90f7df39bc52a82f54c33cefe4047f69f385c4606",
          "sha256": "9816bcaeb4433dfb7c9735b6e032b14213220942b8f82fdad82312a5ecea843f",
          "sha1": "6c79ce7fe797a08b5cee4f4f4af8dc91aaba2bd7",
          "md5": "81eeaea3f6f21573ea4859b628aecb20"
        }
      ]
    }
  ]
}
