{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "securestore-metadata-1.15.0.jar",
          "url": "securestore-1.15.0.jar",
          "size": 7274,
          "sha512": "5f3bd47e43f52722d35aa441fb1535433ad6389fdec1fcc181d04a3848c96ac751b62efb546b58c6993f2a801cb9c37e313a9157dab02575770f9be2b4528718",
          "sha256": "7db1c10258446b708de2d415b5480380a325df8886b0223974098effdb6ff6ac",
          "sha1": "c8ebaeeecd87c8bc586d0dd81b3c10f469731fb3",
          "md5": "b904f869ad2c9f629f352a3ce490c752"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.15.0/securestore-android-debug-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.15.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.15.0/securestore-android-debug-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.15.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.15.0/securestore-android-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.15.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.15.0/securestore-android-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.15.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.15.0/securestore-jvm-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.15.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.15.0/securestore-jvm-1.15.0.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.15.0"
      }
    }
  ]
}
