{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.12.0/util-1.12.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.12.0.klib",
          "size": 25786,
          "sha512": "0f56bce6a007735cb525e5ac8ee6e6775c85af3fba8004e2aac486ecbd1121d60be655c073f0bd4cc085ab4d105fc20705cfe9e0fa7657b595257a0aeec91293",
          "sha256": "6af17d22f5c4ca48e5a34db42b7259e7fdf0735626cc3cd38c93e37e4b27bc35",
          "sha1": "44dfd1995190e6b5ebcf74fa52007ab0fea1fded",
          "md5": "83e401a6d6b5ac26fe80907ad569c4ce"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.12.0-metadata.jar",
          "url": "util-iosarm64-1.12.0-metadata.jar",
          "size": 6109,
          "sha512": "c200e6370e1a6d449ce1129b5e8d80f757b8016f978fbd7017ec4a976935a4cdb54abd4f5fa3393eebe97cfa45098445d954258a96c2848313cd2722eb3e8544",
          "sha256": "09873061d9f892d5cd5515fe1980a09c9f42ea34a551270e9d6dd02c6ec0dfba",
          "sha1": "c3efc615c1851346c89fecc58495f98e0cfcc853",
          "md5": "6e0f443652e5993bfd33421083c87eb2"
        }
      ]
    }
  ]
}
