{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "4aqupfopcfhyxo4ffvhdcoguzq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-metadata-1.13.2.jar",
          "url": "auth-1.13.2.jar",
          "size": 3764,
          "sha512": "0509dd3508ebc0c5951e6e586eafeeeef9736b71989eb886e64333ea3b6359a166faa100fefe6d2e9fd7733a5ece8c3bc20bb0cc184a2a54981244d71c180fc2",
          "sha256": "3b5d93368fd55c733727b195426886ffd0f180cbb1aad7111eddeb14693ea989",
          "sha1": "2f6bd7a934a56082432c0e383a024648a1c0ddf8",
          "md5": "4031eb68463f380bb47293e52ebbc75e"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.13.2/auth-android-debug-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.13.2"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.13.2/auth-android-debug-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.13.2"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.13.2/auth-android-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.13.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.13.2/auth-android-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.13.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.13.2/auth-jvm-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.13.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.13.2/auth-jvm-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.13.2"
      }
    }
  ]
}
