{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2/crypto-1.13.2.module",
    "group": "care.data4life.hc-crypto-kmp",
    "module": "crypto",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "7uw4urucbvb2jew5qn3atydgiq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "65d06df0bbecb77babd796d590f48e370dc59252a4d76b5ab351dd8efe51550ede8e8531de17250dc4fbd8aa3ec884360f6ced64512ef2add299f6e53a194a4d",
          "sha256": "df66a33c7811a798704b86215f9b34976603ef9ef8e6ed8d8a85a3c3106eb541",
          "sha1": "eec50a3f3791f3b0c285491f347783132e095894",
          "md5": "004e9de598bbe369fe42225e9f3f0166"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "65d06df0bbecb77babd796d590f48e370dc59252a4d76b5ab351dd8efe51550ede8e8531de17250dc4fbd8aa3ec884360f6ced64512ef2add299f6e53a194a4d",
          "sha256": "df66a33c7811a798704b86215f9b34976603ef9ef8e6ed8d8a85a3c3106eb541",
          "sha1": "eec50a3f3791f3b0c285491f347783132e095894",
          "md5": "004e9de598bbe369fe42225e9f3f0166"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2/crypto-metadata-1.13.2.module",
        "group": "care.data4life.hc-crypto-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2"
      }
    }
  ]
}
