{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0/test-util-ktor-0.3.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.3.0.klib",
          "size": 15022,
          "sha512": "3d291c11e9b3f75aff17236fbc9623bcbd9894939c2c5c58271ea9ed864d3af7574bd604659172cdcd68edbff2799eecc27690cc720f694a93830d4bc7a32c5a",
          "sha256": "5af24856c803b8c3f286f499368335735a5e25dfd5d16b1f24efaaedc4578a73",
          "sha1": "3db797b886e28be5f28285ea0778f3e4075736b3",
          "md5": "18d3d1b0ae22b016473070a1ba810050"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.3.0-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "687bf0e1ec99e6f07cf6ab6e9688a84b7df33ea9b3eed0ddab376bddac507dc6c3bb02f95ec13f1a35637016eb2fdaa387f57a138cfd8baa30f167906d9c31d7",
          "sha256": "26495353a767c3e36be9738c697c8def0e27108ae315396bcb2e39a02c67ddf7",
          "sha1": "402df6f27e33bb39da9c246101d4728926648fee",
          "md5": "38d72b29991188f2cdc9f6eb0c1c730a"
        }
      ]
    }
  ]
}
