{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto-jvm/1.13.2/crypto-jvm-1.13.2.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "dh2ix7oiezhmxbsc5txrgnzc3a"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.13.2.jar",
          "url": "crypto-metadata-1.13.2.jar",
          "size": 11995,
          "sha512": "1807d284e94e7aff104bd6d77890fbaaf78267788929008338aca870f86fb0772b293998aaf4ec4c8a923e92ff1ecb283d30e78eecd86633aefa28d9bc5ea2a1",
          "sha256": "21c7d53b75afe82513ed82fb67a98617b70e62b1597ba29a40ec4177a64c2386",
          "sha1": "2a19afad4767b6b9fdb626e0527a3a9562f21c8b",
          "md5": "d12437c3000a39725029d66bc415f85e"
        }
      ]
    }
  ]
}
