{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqumllzovzganehrscnruemkz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2.jar",
          "url": "securestore-jvm-1.13.2.jar",
          "size": 16455,
          "sha512": "7afc0a2e83907ace81ec260f05de7000ecf9427251cec3f3a3ad3050c93d9813c14e96de8a446a4c8fb0543389efee23c3b199e7a74b774b486c9686296b0e1f",
          "sha256": "259b1a2404871484d55d1e4139ecb7160aed5f4a68a3c0aa4521c66abd755728",
          "sha1": "05c4bc111d370a0f4b1f52da9aa2dcbeab04f1fc",
          "md5": "9b9b33669c1c7bad5548d28bb7d03397"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2.jar",
          "url": "securestore-jvm-1.13.2.jar",
          "size": 16455,
          "sha512": "7afc0a2e83907ace81ec260f05de7000ecf9427251cec3f3a3ad3050c93d9813c14e96de8a446a4c8fb0543389efee23c3b199e7a74b774b486c9686296b0e1f",
          "sha256": "259b1a2404871484d55d1e4139ecb7160aed5f4a68a3c0aa4521c66abd755728",
          "sha1": "05c4bc111d370a0f4b1f52da9aa2dcbeab04f1fc",
          "md5": "9b9b33669c1c7bad5548d28bb7d03397"
        }
      ]
    }
  ]
}
