{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqumllzovzganehrscnruemkz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2.jar",
          "url": "auth-jvm-1.13.2.jar",
          "size": 34319,
          "sha512": "058f6f2d0f6e1fd8272abc53300ac63c9ebd1fddfeb57e80b77ad51ce679d4168a1ad03326b3eabfb05d291518b3c3c91953144d6fb48c7136daa6c54cc640ea",
          "sha256": "7a3686e4a2e4f97032e9d460cdaf9318544dc0c2ebadc144dfed5b8b7f8e8db9",
          "sha1": "0ad373cd08183787763e69a25488bbf3cae04496",
          "md5": "5a2fff9ed5f9a1dccf35526d51287795"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2.jar",
          "url": "auth-jvm-1.13.2.jar",
          "size": 34319,
          "sha512": "058f6f2d0f6e1fd8272abc53300ac63c9ebd1fddfeb57e80b77ad51ce679d4168a1ad03326b3eabfb05d291518b3c3c91953144d6fb48c7136daa6c54cc640ea",
          "sha256": "7a3686e4a2e4f97032e9d460cdaf9318544dc0c2ebadc144dfed5b8b7f8e8db9",
          "sha1": "0ad373cd08183787763e69a25488bbf3cae04496",
          "md5": "5a2fff9ed5f9a1dccf35526d51287795"
        }
      ]
    }
  ]
}
