{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.2.0/objc-util-0.2.0.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosarm64-0.2.0.klib",
          "size": 8900,
          "sha512": "a378cc690f4a70147cc2fba88d320ae78ddef5a52fc052df495ec2e4e4a4af7dc5248a1da44abfd501841864055003addf0ccaede62ac84131638b462fb94c81",
          "sha256": "632d6a5b32ac7072e3768c3694f4c36cad46bed506a02c2a0652c77cd2a62637",
          "sha1": "57ad6b32232eff5e9d970ce592cb41c91e314d23",
          "md5": "6e049c86649ee63b9999f919da94af76"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosarm64-0.2.0-metadata.jar",
          "url": "objc-util-iosarm64-0.2.0-metadata.jar",
          "size": 5763,
          "sha512": "df7eb9ff4ed386d8464c9ed91023d0f5095562d5f6f41ea6885069f87e45547b07acc8d3bae99c1ae0390de31de7631d7bbfa0ee3f82e3ac7b6ee5e8d49803e3",
          "sha256": "453e800b78cfd85d517e25d8faf05c843a3017b252b363c7509867adafb30493",
          "sha1": "9bc72b984ac0aea3368889f0c7f396589a1ab9dd",
          "md5": "9112112806d399fa6687add1c04f16df"
        }
      ]
    }
  ]
}
