{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7jqgdhmx6bhxdfbmessygnjnem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0.jar",
          "url": "securestore-jvm-1.12.0.jar",
          "size": 16453,
          "sha512": "b6655c3aa2c47bd4290eca34a967d98480a8ed13b74d90231a9b5e1e2180e86a98f56dfa5f312b5d0507dcc41babf728a71327ab7b67f57ac963a26543af39a4",
          "sha256": "d87d7e0359b88dbfcecb58f9c552ca7bd5da190739f7d182636f6506892e9dd4",
          "sha1": "f6543b23ae938e92631f4dffb03e5e253ca60371",
          "md5": "4d0c1870896824cdb7baaaa9e22a8598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0.jar",
          "url": "securestore-jvm-1.12.0.jar",
          "size": 16453,
          "sha512": "b6655c3aa2c47bd4290eca34a967d98480a8ed13b74d90231a9b5e1e2180e86a98f56dfa5f312b5d0507dcc41babf728a71327ab7b67f57ac963a26543af39a4",
          "sha256": "d87d7e0359b88dbfcecb58f9c552ca7bd5da190739f7d182636f6506892e9dd4",
          "sha1": "f6543b23ae938e92631f4dffb03e5e253ca60371",
          "md5": "4d0c1870896824cdb7baaaa9e22a8598"
        }
      ]
    }
  ]
}
