{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.14.0/error-1.14.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "error-jvm-1.14.0.jar",
          "url": "error-jvm-1.14.0.jar",
          "size": 3259,
          "sha512": "d34f16ff7e7ee9056784ef97f0f8cb7a24077fba787382ccc0e46cb14c3ff3327c52a6d90bf19a37ec8d055156a6545b3aad634dfbe48d725a2e3b220d1011bf",
          "sha256": "89ec8af3cb6c8b4deb63b32b1c3ac6eca357538bebf6da2e4463877e3ef13b83",
          "sha1": "f866bd89056a02b279cd5b0301076c1dc460d31b",
          "md5": "39dadedc16f48746c319b4c34803efc7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-jvm-1.14.0.jar",
          "url": "error-jvm-1.14.0.jar",
          "size": 3259,
          "sha512": "d34f16ff7e7ee9056784ef97f0f8cb7a24077fba787382ccc0e46cb14c3ff3327c52a6d90bf19a37ec8d055156a6545b3aad634dfbe48d725a2e3b220d1011bf",
          "sha256": "89ec8af3cb6c8b4deb63b32b1c3ac6eca357538bebf6da2e4463877e3ef13b83",
          "sha1": "f866bd89056a02b279cd5b0301076c1dc460d31b",
          "md5": "39dadedc16f48746c319b4c34803efc7"
        }
      ]
    }
  ]
}
