{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-metadata-1.12.0-all.jar",
          "url": "util-1.12.0-all.jar",
          "size": 6990,
          "sha512": "73b707a2b57d26b31477c50feeb8a30a44cea8d5a61394f34ba8b3c21fba83b8f4fd0e8cc02629394c4e156b489d83cce1d26866fd4c7aba425c0d552facc37c",
          "sha256": "9dde941ad497b951209e96231461861023e154995233eb9a8c7f9586be9d5451",
          "sha1": "69fc82e2d2823452bc136034fe63b772e7733769",
          "md5": "6ba784f6cf934074d1650cb9d1ea1f3f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-1.12.0.jar",
          "url": "util-1.12.0.jar",
          "size": 5398,
          "sha512": "d4345868b86410501f016c9e6f924def76b54d55893386dca43c3760affd8e60694da5601e9bd5d37d14343597f7d1871d29c043d915e25ad5e4a5604148f99b",
          "sha256": "c864e3f6ba7fd2489855b0c0028af2f7d2f44e4d8bc29868500f8e65bdd8762f",
          "sha1": "171afdede3ae359dced34b4cb7237d3a16e80b62",
          "md5": "f49a7b9aa46289f57faca90598f234bd"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.12.0/util-android-debug-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.12.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.12.0/util-android-debug-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.12.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.12.0/util-android-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.12.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.12.0/util-android-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosarm64/1.12.0/util-iosarm64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosarm64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosarm64/1.12.0/util-iosarm64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosarm64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosx64/1.12.0/util-iosx64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosx64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosx64/1.12.0/util-iosx64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosx64",
        "version": "1.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.12.0/util-jvm-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.12.0/util-jvm-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.12.0"
      }
    }
  ]
}
