{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqumllzovzganehrscnruemkz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2.jar",
          "url": "auth-common-1.13.2.jar",
          "size": 3578,
          "sha512": "b60b4fe1ab40c378eacd5152cd77d51354ae489c4463ae4a13933c598b2bff2eb47220b6c21b5120cadad46003256f297623922c683d117bae03f5ddbe10f4a7",
          "sha256": "e54d3cd91fff0ab00cc0e47796a51e7dca309832addd6f621bed6748ce894716",
          "sha1": "39382a93cbcda151e04e0bef41290cb8f2469bdd",
          "md5": "4caec884340b583faeba7ba609a6dddd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2.jar",
          "url": "auth-common-1.13.2.jar",
          "size": 3578,
          "sha512": "b60b4fe1ab40c378eacd5152cd77d51354ae489c4463ae4a13933c598b2bff2eb47220b6c21b5120cadad46003256f297623922c683d117bae03f5ddbe10f4a7",
          "sha256": "e54d3cd91fff0ab00cc0e47796a51e7dca309832addd6f621bed6748ce894716",
          "sha1": "39382a93cbcda151e04e0bef41290cb8f2469bdd",
          "md5": "4caec884340b583faeba7ba609a6dddd"
        }
      ]
    }
  ]
}
