{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0/util-1.11.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.11.0.jar",
          "url": "util-jvm-1.11.0.jar",
          "size": 15643,
          "sha512": "71233be717b82c845e0ae51cfd9ab286c47d74f7c7108faf04a7017d3d3ec475b791839a7553b491148995f7717d9eef2208a18ae174f45f79fcf5de0fb67f48",
          "sha256": "6cd5fc9ac4195b363e67bebaf215e6f0800b01bf1a53b832b77c7d29b4ca3d0c",
          "sha1": "ed413adbcb4e7621462ef42cb22a96084153f875",
          "md5": "b90fffdf00417491a9bf6fc5157f1358"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.11.0.jar",
          "url": "util-jvm-1.11.0.jar",
          "size": 15643,
          "sha512": "71233be717b82c845e0ae51cfd9ab286c47d74f7c7108faf04a7017d3d3ec475b791839a7553b491148995f7717d9eef2208a18ae174f45f79fcf5de0fb67f48",
          "sha256": "6cd5fc9ac4195b363e67bebaf215e6f0800b01bf1a53b832b77c7d29b4ca3d0c",
          "sha1": "ed413adbcb4e7621462ef42cb22a96084153f875",
          "md5": "b90fffdf00417491a9bf6fc5157f1358"
        }
      ]
    }
  ]
}
