{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1.jar",
          "url": "securestore-common-1.13.1.jar",
          "size": 6926,
          "sha512": "9563eb946fcdc95cccaaa5dcdae3635af5ec13c787020eade817c27abe5136532112ca1ed6c47c2f45cc51f8c3748784350cecc247f9861ebed5fa13c35463c7",
          "sha256": "5a0cd6457e2095153b2a59a7934a90e2b938b5e74bcf3a33ca21d7db4bd49f41",
          "sha1": "618344feca233dab6d65a22af85bf6f60ceb2034",
          "md5": "52b8d0dce45c71ac5e5df632a7c1ec3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1.jar",
          "url": "securestore-common-1.13.1.jar",
          "size": 6926,
          "sha512": "9563eb946fcdc95cccaaa5dcdae3635af5ec13c787020eade817c27abe5136532112ca1ed6c47c2f45cc51f8c3748784350cecc247f9861ebed5fa13c35463c7",
          "sha256": "5a0cd6457e2095153b2a59a7934a90e2b938b5e74bcf3a33ca21d7db4bd49f41",
          "sha1": "618344feca233dab6d65a22af85bf6f60ceb2034",
          "md5": "52b8d0dce45c71ac5e5df632a7c1ec3f"
        }
      ]
    }
  ]
}
