{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0.jar",
          "url": "sdk-jvm-1.14.0.jar",
          "size": 11617,
          "sha512": "013a07515709b9b60e872f087f7bf60131c6895fd8c775adcde4afd9a971bd91d61ab15216c14732dc8faa6af1ff4ccaf58b8e7deb66ed53f7f4ba0863a2e635",
          "sha256": "9d29f7f16bb6ae6d0de52b8003ad4680cd6b164dbace4feded9551951802e714",
          "sha1": "acbe8934b62e6981f4cf59e21fb319e0b76f4afb",
          "md5": "56b8ec42ab21d9c8906f05910cc40774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0.jar",
          "url": "sdk-jvm-1.14.0.jar",
          "size": 11617,
          "sha512": "013a07515709b9b60e872f087f7bf60131c6895fd8c775adcde4afd9a971bd91d61ab15216c14732dc8faa6af1ff4ccaf58b8e7deb66ed53f7f4ba0863a2e635",
          "sha256": "9d29f7f16bb6ae6d0de52b8003ad4680cd6b164dbace4feded9551951802e714",
          "sha1": "acbe8934b62e6981f4cf59e21fb319e0b76f4afb",
          "md5": "56b8ec42ab21d9c8906f05910cc40774"
        }
      ]
    }
  ]
}
