{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.16.1.jar",
          "url": "crypto-1.16.1.jar",
          "size": 670,
          "sha512": "2d3065d8258cd68a7d6659b73b71b4026fddb26fe903b8ba2a81a9e66e46c4099a64a4ab7961e5d32f9bfdda2c11d2c421882478d84dff77e72f6bd4c465ca9e",
          "sha256": "5e63fbee9c8451a7b345dd5e0a770e8403133e61a67c5e8a0205ef414f593492",
          "sha1": "446aa5d1b9691328f4278b463b439d1a513695b4",
          "md5": "5c43c6afa143a767a81df160f503b028"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.16.1/crypto-android-debug-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.16.1"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.16.1/crypto-android-debug-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.16.1"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.16.1/crypto-android-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.16.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.16.1/crypto-android-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.16.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.16.1/crypto-jvm-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.16.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.16.1/crypto-jvm-1.16.1.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.16.1"
      }
    }
  ]
}
