{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0/test-util-ktor-0.3.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0.jar",
          "url": "test-util-ktor-jvm-0.3.0.jar",
          "size": 28636,
          "sha512": "8bb185fde39448eb3794a0ce95a7db5e92ca0772daf4bafd0e0104a51be6d9101337cdc84d074b5d9c8cfe354a55973a4d14461a0c9f709c11e380c05d235fa0",
          "sha256": "168371e6bbac734106ddac27ac8d39f302317c642d146d7373c22ccf8ca900b1",
          "sha1": "3a9e120cd962ca1142ba222cff6e5661b81bf597",
          "md5": "315cd2f91b0acf62f44607caa03d4ce6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0.jar",
          "url": "test-util-ktor-jvm-0.3.0.jar",
          "size": 28636,
          "sha512": "8bb185fde39448eb3794a0ce95a7db5e92ca0772daf4bafd0e0104a51be6d9101337cdc84d074b5d9c8cfe354a55973a4d14461a0c9f709c11e380c05d235fa0",
          "sha256": "168371e6bbac734106ddac27ac8d39f302317c642d146d7373c22ccf8ca900b1",
          "sha1": "3a9e120cd962ca1142ba222cff6e5661b81bf597",
          "md5": "315cd2f91b0acf62f44607caa03d4ce6"
        }
      ]
    }
  ]
}
