{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.14.0/util-1.14.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.14.0.klib",
          "size": 25794,
          "sha512": "6ac58d5a9bea013c82f76e95424752bc3eeb2624c3ff220e805665c0788a49cb7b9e4faa3f556f61699401cc9e6b487f4ecdf712d1d299ad6403440e85855401",
          "sha256": "796531085200bcb6577a78ebb4e1336c2ded111d8901bab0f9c28a0aeec36577",
          "sha1": "6d4d0cdff904288483d5bd1df72a2bec7d098b66",
          "md5": "28fd600ecbb451fb4bc45e5b42e61b50"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.14.0-metadata.jar",
          "url": "util-iosarm64-1.14.0-metadata.jar",
          "size": 6142,
          "sha512": "2de1572397ec6ad58d9f9067602d419e0f56a64ce9492bde50b2fc2ed976acb990dbbe052397877660b0e85f34009566ba7707d9eaf5a3ba41361167673ec864",
          "sha256": "f903beb9ed02b398b5077e754bb4f8797f002889f20f83f7f14cce5bb183f607",
          "sha1": "3ec013fc03935fabab66bf11d45eb89914ed636b",
          "md5": "4fe7afee95b947f21080877da5be087b"
        }
      ]
    }
  ]
}
