{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test-jvm/1.9.0/util-ktor-test-jvm-1.9.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test-jvm",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aitrtwsoyvbztl5swknjdi3ioi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-ktor-test-metadata-1.9.0.jar",
          "url": "util-ktor-test-metadata-1.9.0.jar",
          "size": 3186,
          "sha512": "8104161588b14e86813f72c503fce6a07695be71aee92c1f9bdeddf1fa0bd3c1fbbefca3f4e638515d44361c0e288b593b7acc967bb0499bb5ba44df49b0fb7a",
          "sha256": "257efac917f5e2d9ebed84af7d2cd81b15e2aa0bc465d39137bac7af8303c29e",
          "sha1": "67f2dca1ecc85b189654d2525b269036423c750e",
          "md5": "2eb01090815df51088658dec183e6af8"
        }
      ]
    }
  ]
}
