{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.2.0/objc-util-0.2.0.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosx64-0.2.0.klib",
          "size": 8882,
          "sha512": "ba9439706673c7bce71692adf48cb14c1056a107c7dacdf696d227e7f40d7b0bd875d6b5d13e711b81f0f836760266c51296208a666c69a2f691dd8a7710f7a0",
          "sha256": "1be2bdcfb0c3bdf00528903465345ccf5e0f9b5cffcbe284688ad14080fff55a",
          "sha1": "3927b4af7a5de28dee43fbdde2074d611f9ce2fe",
          "md5": "6680587c64d67f1afb31799b872d2972"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosx64-0.2.0-metadata.jar",
          "url": "objc-util-iosx64-0.2.0-metadata.jar",
          "size": 5763,
          "sha512": "df7eb9ff4ed386d8464c9ed91023d0f5095562d5f6f41ea6885069f87e45547b07acc8d3bae99c1ae0390de31de7631d7bbfa0ee3f82e3ac7b6ee5e8d49803e3",
          "sha256": "453e800b78cfd85d517e25d8faf05c843a3017b252b363c7509867adafb30493",
          "sha1": "9bc72b984ac0aea3368889f0c7f396589a1ab9dd",
          "md5": "9112112806d399fa6687add1c04f16df"
        }
      ]
    }
  ]
}
