{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-metadata-1.13.0-all.jar",
          "url": "error-1.13.0-all.jar",
          "size": 3914,
          "sha512": "d937a0078152a2ec47ce9f658f85cbfefc11936ff87d3797d4afbee6ebdd1e2b6773445303723a386767680bf1be09203a89f0674829b06df76c4f8907a10c77",
          "sha256": "2b9803ad07e0e1507af3c0f74998d388cae7d7d0ce5fd4959032746f1a9b4818",
          "sha1": "aa4eb75a3e30a955968665ea7435f1093ec01974",
          "md5": "c94ed9c81c6d3cd187cc7d32d05a9dec"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "error-1.13.0.jar",
          "url": "error-1.13.0.jar",
          "size": 1921,
          "sha512": "54a8ed0c81ac47393b175dad9c5cf477729d2deab08a918eee034b82ad6455de9d6a7378ceb857268e65d48ab69893a818a08d98f30dbc081f82e8c3f1fbf825",
          "sha256": "29f4033e8ea453fc0c26fd23435ee684fddb5fc95bd4d9938f873d95cf18a5b2",
          "sha1": "b0d9b470c91079516745406ecb61dc8b52d3dbf9",
          "md5": "dc7db88b8a1430042cfbdc256388b302"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android-debug/1.13.0/error-android-debug-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android-debug",
        "version": "1.13.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android-debug/1.13.0/error-android-debug-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android-debug",
        "version": "1.13.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android/1.13.0/error-android-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android",
        "version": "1.13.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android/1.13.0/error-android-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android",
        "version": "1.13.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosarm64/1.13.0/error-iosarm64-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosarm64",
        "version": "1.13.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosarm64/1.13.0/error-iosarm64-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosarm64",
        "version": "1.13.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosx64/1.13.0/error-iosx64-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosx64",
        "version": "1.13.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosx64/1.13.0/error-iosx64-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosx64",
        "version": "1.13.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../error-jvm/1.13.0/error-jvm-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-jvm",
        "version": "1.13.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../error-jvm/1.13.0/error-jvm-1.13.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-jvm",
        "version": "1.13.0"
      }
    }
  ]
}
