{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7jqgdhmx6bhxdfbmessygnjnem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0.jar",
          "url": "auth-common-1.12.0.jar",
          "size": 3578,
          "sha512": "f1f75796d474ef09f29bdc1e02b6be6c53d588e01a44ee1fb7d98d3d804b4b65468490521ca2b18f57b5249490e2e56ee04d5450f7373c825debc6d4dbedf3c3",
          "sha256": "e2479134cd941efb912f16c9de6c1f1ca487d358c29ad0fcdedebcb986a42cd4",
          "sha1": "56f8dda44380d5ac3ce45d39c3ddaf04e905931d",
          "md5": "f2d439feae79f797623aaa3f39975de4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0.jar",
          "url": "auth-common-1.12.0.jar",
          "size": 3578,
          "sha512": "f1f75796d474ef09f29bdc1e02b6be6c53d588e01a44ee1fb7d98d3d804b4b65468490521ca2b18f57b5249490e2e56ee04d5450f7373c825debc6d4dbedf3c3",
          "sha256": "e2479134cd941efb912f16c9de6c1f1ca487d358c29ad0fcdedebcb986a42cd4",
          "sha1": "56f8dda44380d5ac3ce45d39c3ddaf04e905931d",
          "md5": "f2d439feae79f797623aaa3f39975de4"
        }
      ]
    }
  ]
}
