{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1.jar",
          "url": "securestore-jvm-1.13.1.jar",
          "size": 16453,
          "sha512": "8cd2c077c62da487699b4a9b7df0765d91eeec6ce9732d89688a6cae57030c1b99ac51ee3c93941bbe937567468849648af4370d8e27a210406e55dc83fad146",
          "sha256": "9a401c9ec538c0d828a3c0dc26c681802a4c9f98499e41367185e89f1649129f",
          "sha1": "ac2c0c5aaf1416f841aff5d8c0938469a8be0c0b",
          "md5": "af949731a6afab607c9704b4bf1123c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1.jar",
          "url": "securestore-jvm-1.13.1.jar",
          "size": 16453,
          "sha512": "8cd2c077c62da487699b4a9b7df0765d91eeec6ce9732d89688a6cae57030c1b99ac51ee3c93941bbe937567468849648af4370d8e27a210406e55dc83fad146",
          "sha256": "9a401c9ec538c0d828a3c0dc26c681802a4c9f98499e41367185e89f1649129f",
          "sha1": "ac2c0c5aaf1416f841aff5d8c0938469a8be0c0b",
          "md5": "af949731a6afab607c9704b4bf1123c1"
        }
      ]
    }
  ]
}
