{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uaqlyonijvbj3jsaxzmoi6suce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "da6290d5a2d61c65b78e71c09db3b39cb7188061d5ce14d8e2ef0ac31621cc0a13dfa494fd386911811af8477edef8ab60e258289c9d3bbfe2ef2c3878036fa6",
          "sha256": "ddfe435652fec1a32ff3ae3847df41f3fc4672cc5845d500d22b3c32f687766e",
          "sha1": "9dd4874b52737829ffe170209bcb177955cda7c2",
          "md5": "8cb77697edc660031516c7da2a194d18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "da6290d5a2d61c65b78e71c09db3b39cb7188061d5ce14d8e2ef0ac31621cc0a13dfa494fd386911811af8477edef8ab60e258289c9d3bbfe2ef2c3878036fa6",
          "sha256": "ddfe435652fec1a32ff3ae3847df41f3fc4672cc5845d500d22b3c32f687766e",
          "sha1": "9dd4874b52737829ffe170209bcb177955cda7c2",
          "md5": "8cb77697edc660031516c7da2a194d18"
        }
      ]
    }
  ]
}
