{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.12.0/error-1.12.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.12.0.klib",
          "size": 7100,
          "sha512": "6a4f00dfb2e9216859511612f28936ad8d04a46f89f7a35e065c792f2aebbbed129bc6e9fa6fd75be69976280c1af7bd9f7fa7b9da6b0b7a07a1d9e5bcb18f2a",
          "sha256": "0b55087a1d26b454ca975f26d916e1a2c1683541cac36e4bb3c83814aea82ef9",
          "sha1": "ae441be4e76b509af8a51da13be61d0a4466d154",
          "md5": "b4f80a90b3d3852b8bb6054d132887c1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.12.0-metadata.jar",
          "url": "error-iosarm64-1.12.0-metadata.jar",
          "size": 5010,
          "sha512": "44272c3aaf2a5f65d4fc41346f98593f3bd93bb391f4eb696660fe515dacd30f5188104445e77218bb77a472d932650e7014dda2b7a87f6b4c0600cb322bd006",
          "sha256": "24810956cb855f04c74fb6211890301d342cf7f0289fd537f98bf66455bbe93b",
          "sha1": "a2c4824514a4bfe11199328eb5d0bcbde6de9f3f",
          "md5": "d92bc16706285f25da05b8161bb813c9"
        }
      ]
    }
  ]
}
