{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.13.0/error-1.13.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.13.0.klib",
          "size": 7100,
          "sha512": "6a4f00dfb2e9216859511612f28936ad8d04a46f89f7a35e065c792f2aebbbed129bc6e9fa6fd75be69976280c1af7bd9f7fa7b9da6b0b7a07a1d9e5bcb18f2a",
          "sha256": "0b55087a1d26b454ca975f26d916e1a2c1683541cac36e4bb3c83814aea82ef9",
          "sha1": "ae441be4e76b509af8a51da13be61d0a4466d154",
          "md5": "b4f80a90b3d3852b8bb6054d132887c1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.13.0-metadata.jar",
          "url": "error-iosarm64-1.13.0-metadata.jar",
          "size": 5010,
          "sha512": "e7278b0022c96f1ce04b8b6d65522e23a79f5bf8ba1238c6ff7b2c5b0fa7a061cd7cf1fa818af7ac7c54cabec07c61518e47d1cbca4e98990e3bfa7007588c62",
          "sha256": "34fea5fa88121550453c290ba1b47a35348ad078a10a5bf4e5b77733c64c25d7",
          "sha1": "b7ff0f1d7ea9e4efa12dba43fe985abf28f5ab34",
          "md5": "303487de35f93528c634657a4f130227"
        }
      ]
    }
  ]
}
