{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0/test-util-ktor-0.2.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "5yqcthc63vakhp7dyx6anr62ie"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0.jar",
          "url": "test-util-ktor-jvm-0.2.0.jar",
          "size": 28646,
          "sha512": "8223230e6d225c3a700c01760d81c9e90b98420c5004cdcc90d29039da458e7f2aa4d77a16c9c0a0a326ea8ace650673c495ae512063c752ee1bcc3a46fb53ed",
          "sha256": "0a3c5057c9a81441d93030f487050d45836028b09b361c112408bf6db2288199",
          "sha1": "576824f99cc88bed1b73902d4eee5361fb2a94f3",
          "md5": "db412e6c12d3ad2ab3b45d197a196961"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0.jar",
          "url": "test-util-ktor-jvm-0.2.0.jar",
          "size": 28646,
          "sha512": "8223230e6d225c3a700c01760d81c9e90b98420c5004cdcc90d29039da458e7f2aa4d77a16c9c0a0a326ea8ace650673c495ae512063c752ee1bcc3a46fb53ed",
          "sha256": "0a3c5057c9a81441d93030f487050d45836028b09b361c112408bf6db2288199",
          "sha1": "576824f99cc88bed1b73902d4eee5361fb2a94f3",
          "md5": "db412e6c12d3ad2ab3b45d197a196961"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.2.0/test-util-ktor-metadata-0.2.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.2.0"
      }
    }
  ]
}
