{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.14.0.jar",
          "url": "securestore-common-1.14.0.jar",
          "size": 6926,
          "sha512": "5a645171d414f22b8d8f1eb0d33bda7635fac90c08dffe68f126c4ef83044aa2588294f71e2230e900fae23f6b37e0d82a47789ae8b1f489bb684b7c95b22ea9",
          "sha256": "23e172c60e0e555ebe4e7541d3842776a15133fc27282422fc1500be67b62ba2",
          "sha1": "794da1d8a92a00e7babb7f16ae4900cd954dd3d9",
          "md5": "11829087197deb074e3ef4a34b1bfb2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.14.0.jar",
          "url": "securestore-common-1.14.0.jar",
          "size": 6926,
          "sha512": "5a645171d414f22b8d8f1eb0d33bda7635fac90c08dffe68f126c4ef83044aa2588294f71e2230e900fae23f6b37e0d82a47789ae8b1f489bb684b7c95b22ea9",
          "sha256": "23e172c60e0e555ebe4e7541d3842776a15133fc27282422fc1500be67b62ba2",
          "sha1": "794da1d8a92a00e7babb7f16ae4900cd954dd3d9",
          "md5": "11829087197deb074e3ef4a34b1bfb2e"
        }
      ]
    }
  ]
}
