{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0/test-util-0.3.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.3.0.klib",
          "size": 16564,
          "sha512": "8960e586d765f9deea7c3cf39719c4158174eaf73c9ed3a65d940587f810255ba6564417fda14053c1408d346f678e61fd1844091426c84d50301ed8c4c89255",
          "sha256": "12eb2c43fe5e275fdab2bc7d2a7f43ddab0bd72706314379164bc4491538da6b",
          "sha1": "da13985eea5e66c11571c21ef792d8f60f036d0f",
          "md5": "910cf550bac1f51c612225e64de375fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosarm64-0.3.0-metadata.jar",
          "url": "test-util-iosarm64-0.3.0-metadata.jar",
          "size": 7055,
          "sha512": "9e1acbf41e48693897196c32bb6fce81a5fa1632fc7c76b9128aff3bd67acc4dfbc32caf766d4707ef7fdd8bf85cde8c7d127d895fcc143893a586f60b78efeb",
          "sha256": "aa67e2cad928a8d942d0a6c6a654799ebd7a4a3778f42a7d7cfc7b0b218725f0",
          "sha1": "f66828747c77d40dd29f8df7f0c0c4baf2d0fd78",
          "md5": "51a0519b2a072da7486602fbdaa8df45"
        }
      ]
    }
  ]
}
