{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0/test-util-coroutine-0.2.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "5yqcthc63vakhp7dyx6anr62ie"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0.jar",
          "url": "test-util-coroutine-jvm-0.2.0.jar",
          "size": 5987,
          "sha512": "3f3d581d8a66550a5b81e1e32acc3fdaba8bfbebddde4dcf8f269d77fa5f514364a785d2c18b3d26bd508f1b78d7e08cfe34b9f1a6e17615b362f044666b85eb",
          "sha256": "bfe9e39a577d055d9394a6a13bcb70cf74d6a50e3b4d037e9b04444e8fb1e572",
          "sha1": "74acab839ae65a737af4582d6b6668d965b76600",
          "md5": "ff179d64ceafd04920dc45a0bc8809bf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0.jar",
          "url": "test-util-coroutine-jvm-0.2.0.jar",
          "size": 5987,
          "sha512": "3f3d581d8a66550a5b81e1e32acc3fdaba8bfbebddde4dcf8f269d77fa5f514364a785d2c18b3d26bd508f1b78d7e08cfe34b9f1a6e17615b362f044666b85eb",
          "sha256": "bfe9e39a577d055d9394a6a13bcb70cf74d6a50e3b4d037e9b04444e8fb1e572",
          "sha1": "74acab839ae65a737af4582d6b6668d965b76600",
          "md5": "ff179d64ceafd04920dc45a0bc8809bf"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.2.0/test-util-coroutine-metadata-0.2.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.2.0"
      }
    }
  ]
}
