{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0.jar",
          "url": "securestore-jvm-1.14.0.jar",
          "size": 16455,
          "sha512": "1e0d944e500729101c514ab0fbd6c717781d2e20af19af043545613314f3610b335c4c8b37ddfe35423ed22ee5eb955c72ab78f8f4e8ea614d4417a7891eb49c",
          "sha256": "f74d0108e98fb13858ec4e7d72268d50104e079e3fc57622ac80e44e5ab93f4d",
          "sha1": "8faef39b73b86eea51e48cb72c802f763d2ce115",
          "md5": "dfefdc86121be5fc23576e33412628fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0.jar",
          "url": "securestore-jvm-1.14.0.jar",
          "size": 16455,
          "sha512": "1e0d944e500729101c514ab0fbd6c717781d2e20af19af043545613314f3610b335c4c8b37ddfe35423ed22ee5eb955c72ab78f8f4e8ea614d4417a7891eb49c",
          "sha256": "f74d0108e98fb13858ec4e7d72268d50104e079e3fc57622ac80e44e5ab93f4d",
          "sha1": "8faef39b73b86eea51e48cb72c802f763d2ce115",
          "md5": "dfefdc86121be5fc23576e33412628fc"
        }
      ]
    }
  ]
}
