{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2/crypto-1.13.2.module",
    "group": "care.data4life.sdk.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ixhfp3evpjeednbpq7q4fbwdmq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "f0cafd5f4c1f0cfbe2fa1e2afbc4b13fb908dd9d18d0e364e5d3e51722e23168c2b53b3bf7360e27853e36b86c98b3023b26f3daff3f3bc6bee33321b1fc77ba",
          "sha256": "cb9d560c80670c152a93ac99d90943dbf2ea440b8469372ea23b75724a1edb2b",
          "sha1": "018905fd0de99f125c27b2b3d2925b714b785a6f",
          "md5": "d4bc9377506f5a1b5fb5a7d8929768eb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "f0cafd5f4c1f0cfbe2fa1e2afbc4b13fb908dd9d18d0e364e5d3e51722e23168c2b53b3bf7360e27853e36b86c98b3023b26f3daff3f3bc6bee33321b1fc77ba",
          "sha256": "cb9d560c80670c152a93ac99d90943dbf2ea440b8469372ea23b75724a1edb2b",
          "sha1": "018905fd0de99f125c27b2b3d2925b714b785a6f",
          "md5": "d4bc9377506f5a1b5fb5a7d8929768eb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2/crypto-metadata-1.13.2.module",
        "group": "care.data4life.sdk.hc-crypto-sdk-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2"
      }
    }
  ]
}
