{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.3.0-all.jar",
          "url": "test-util-coroutine-0.3.0-all.jar",
          "size": 5018,
          "sha512": "b982022d761d6fdd4a18c931f283213745da714e0d4951f0a25b27d04c9adb9e34903ed713e1ab2df4bc001b1eb5c18945c1f414d9a19e284dc634bdce077be4",
          "sha256": "009d6f2b1eb8cca940a9bb7c661a3f50db74444c9960dfcec167b677ef4f6e89",
          "sha1": "28001fde58f1239d9f7640bcb7fdbd949c26146c",
          "md5": "a73d04297cfe83f1fbf156650023bcba"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-0.3.0.jar",
          "url": "test-util-coroutine-0.3.0.jar",
          "size": 1774,
          "sha512": "3ffcff979df5387234d892d31a19cdc4fcbcede5af546cdcf4bf1cc4fe08200577c6520849703dce662c29c6859a89e70a95b1ff6b4bdbf6825ef69bb20952a3",
          "sha256": "1629edaf4e763abfcac06d4eb556b6fe641aaf3290db89cb01ccf63765c8b0b4",
          "sha1": "b18e933483c240ac3a030335e501050b8d1fd2ce",
          "md5": "390cb0075c411bb408aa0331162a7976"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.3.0/test-util-coroutine-android-debug-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.3.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.3.0/test-util-coroutine-android-debug-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.3.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.3.0/test-util-coroutine-android-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.3.0/test-util-coroutine-android-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.3.0/test-util-coroutine-iosarm64-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.3.0/test-util-coroutine-iosarm64-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.3.0/test-util-coroutine-iosx64-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.3.0/test-util-coroutine-iosx64-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.3.0/test-util-coroutine-jvm-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.3.0/test-util-coroutine-jvm-0.3.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.3.0"
      }
    }
  ]
}
