{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.5.0/test-util-coroutine-0.5.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.5.0.klib",
          "size": 8272,
          "sha512": "4c3c4a90602d30707b1eb3165a58fdf92a0ec63bbcdcbda20826d498049ad65d1696b02722ea05ca9b73ac70fbbc275042669ccdcb9b650cc395bc4cfb289fb3",
          "sha256": "a2b518d7a6d40a40e6f1e86c9f094ede222be6f1b9d7d640988e0f471f0b1029",
          "sha1": "361236d351c6a2be889f858eafc5c692bfe5821d",
          "md5": "16df4621e58ddbf50aa30316055997b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.5.0-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.5.0-metadata.jar",
          "size": 6287,
          "sha512": "5e562567302fe84c589ecfc06bf0f49bd4364b1b7a685cf8cc7ba181f95026c00c78e94dba98e1117c8c52a15b8524c6f37ee968d181dd5996b975651285d3fa",
          "sha256": "d7c49b17059fd079897ae5ec09169ebc875b5e8e841293316ba0a91a4f06cd88",
          "sha1": "178ad3857665b85ecdcce9f0e99eda4c01a3053d",
          "md5": "e05c417d2b7b3d30ccfe5f6aea0e86a4"
        }
      ]
    }
  ]
}
