{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1.jar",
          "url": "auth-jvm-1.13.1.jar",
          "size": 34318,
          "sha512": "ccaf5b57e0a339b0c71c60e25657076bb5ca57d43aaa809e55ac69f0b3e6032a821dc21d45f7d46bd9fff9bf409f5e196205e5ff90ed3bc9268017266ac3e479",
          "sha256": "29ffd3f428b79892845a787f691fc0402554d9181dd33b064cf3326b42eb736a",
          "sha1": "d35e05c2cd9b488070857359402a0d5ec39b3ffc",
          "md5": "624c2d73ae0b83a1901b38743a052ffd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1.jar",
          "url": "auth-jvm-1.13.1.jar",
          "size": 34318,
          "sha512": "ccaf5b57e0a339b0c71c60e25657076bb5ca57d43aaa809e55ac69f0b3e6032a821dc21d45f7d46bd9fff9bf409f5e196205e5ff90ed3bc9268017266ac3e479",
          "sha256": "29ffd3f428b79892845a787f691fc0402554d9181dd33b064cf3326b42eb736a",
          "sha1": "d35e05c2cd9b488070857359402a0d5ec39b3ffc",
          "md5": "624c2d73ae0b83a1901b38743a052ffd"
        }
      ]
    }
  ]
}
