{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.0/data-donation-sdk-iosx64-0.2.0.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xctgctralrahxomp6obgqvgblu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.0.jar",
          "url": "data-donation-sdk-metadata-0.2.0.jar",
          "size": 58853,
          "sha512": "d048231400fa10865ab46076ed7daae01d68fcc5d9b9abc9fe77e31121f56a69eb56c2bfc165f2830f83567be2a64d7c49268ec20c479c097eb6312f05b0a597",
          "sha256": "95daf1fb57680d81758cea3e70ddf55e2991fbfa85ffcd0873b894bcbb30ddb0",
          "sha1": "5df1e908465739076fe97beab64fead1e678a233",
          "md5": "3573fe0ca2bdad976056619625081e89"
        }
      ]
    }
  ]
}
