{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.14.0/util-1.14.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.14.0.jar",
          "url": "util-jvm-1.14.0.jar",
          "size": 15430,
          "sha512": "fe2da0b9369ee38290d1f85cc3af12ca37f15f2b564e678a525dcc86f1b631755db30d4650cfa32b5f5674df5c0635a40ae5e9ac2d9e3662a5b5c86940ae02c1",
          "sha256": "4c0400c05c434e69552f95baf38a180f61ea2343c83ce3bdc576a0368aae09da",
          "sha1": "d397564347d659616da49644878f515aef7a41c3",
          "md5": "f2952f76b03981c785d4b6870913944a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.14.0.jar",
          "url": "util-jvm-1.14.0.jar",
          "size": 15430,
          "sha512": "fe2da0b9369ee38290d1f85cc3af12ca37f15f2b564e678a525dcc86f1b631755db30d4650cfa32b5f5674df5c0635a40ae5e9ac2d9e3662a5b5c86940ae02c1",
          "sha256": "4c0400c05c434e69552f95baf38a180f61ea2343c83ce3bdc576a0368aae09da",
          "sha1": "d397564347d659616da49644878f515aef7a41c3",
          "md5": "f2952f76b03981c785d4b6870913944a"
        }
      ]
    }
  ]
}
