{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uaqlyonijvbj3jsaxzmoi6suce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.0-SNAPSHOT.jar",
          "url": "auth-common-1.13.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "00083130eeae8848d4272cd8088d1e18432d63fc8d955fa864ff165aeea0a336e2aedad938bd317d39beeb75581d144e51cb1524d713feef8d7455bf8739f7da",
          "sha256": "21db2f7ff7ab163cc824f2c0e685904c1bce52aa7f726dc7eab8ecf288701f46",
          "sha1": "e8499cdf6c5dd10a167f4f460007777e3bc768d0",
          "md5": "c3527ac8861893cd2c725ddbc97bcfa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.0-SNAPSHOT.jar",
          "url": "auth-common-1.13.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "00083130eeae8848d4272cd8088d1e18432d63fc8d955fa864ff165aeea0a336e2aedad938bd317d39beeb75581d144e51cb1524d713feef8d7455bf8739f7da",
          "sha256": "21db2f7ff7ab163cc824f2c0e685904c1bce52aa7f726dc7eab8ecf288701f46",
          "sha1": "e8499cdf6c5dd10a167f4f460007777e3bc768d0",
          "md5": "c3527ac8861893cd2c725ddbc97bcfa4"
        }
      ]
    }
  ]
}
