{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.5.0/test-util-0.5.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.5.0.klib",
          "size": 17519,
          "sha512": "820737284bbf4ab160d45aba479754655983b0e7c2432ff18c68766e6640c202ce33b2b9a66af0ae82d36eb820a6354eb06e6837c0cb466e70299dfcfe83a0fb",
          "sha256": "51a0e93ec267424a33e94cbceffdbe9c3a576ca0f57208cf4d8b4caee2b4d09a",
          "sha1": "12b6f2c8e23bcfbc5c7c9e6a3fd59a327787a78a",
          "md5": "a58951b506ffce78c1d345cf1d80a6e9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosarm64-0.5.0-metadata.jar",
          "url": "test-util-iosarm64-0.5.0-metadata.jar",
          "size": 7055,
          "sha512": "cb1ee1eceb44a2fedb8a261cdf1ba18c9bccc836c820e5d445b959ee79c7fe67aff4aa77adab0fa0b2397925f3cb229b88f8faf6f5d0b5ed397b891e0eebcbcc",
          "sha256": "fb46695b3b5d69a75d946da6cd2e3428256caf55b3afdbe05a8321934673a062",
          "sha1": "80b27e95f4bfba3d270b647ca579562984f7228f",
          "md5": "dd84abcab3529d2c3f0a36512b37f1b6"
        }
      ]
    }
  ]
}
