{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.1.jar",
          "url": "crypto-common-1.13.1.jar",
          "size": 11519,
          "sha512": "3dc30c74754c3bb780468a92aa915e634cae7613c00e70c9c427be9f1b5014331c1638209f20c95f35ad0da97a2487048ffbd7b14181034a8135c9a128561492",
          "sha256": "297946a7b0e42d3084b7bfe901c2dfa57df40186cd5dc5e58a06d1c5c677c8cd",
          "sha1": "6d6be82f5b4a9b350608f5617bad9954713466f4",
          "md5": "16670d886f29cb8f149ebb62768acf80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.1.jar",
          "url": "crypto-common-1.13.1.jar",
          "size": 11519,
          "sha512": "3dc30c74754c3bb780468a92aa915e634cae7613c00e70c9c427be9f1b5014331c1638209f20c95f35ad0da97a2487048ffbd7b14181034a8135c9a128561492",
          "sha256": "297946a7b0e42d3084b7bfe901c2dfa57df40186cd5dc5e58a06d1c5c677c8cd",
          "sha1": "6d6be82f5b4a9b350608f5617bad9954713466f4",
          "md5": "16670d886f29cb8f149ebb62768acf80"
        }
      ]
    }
  ]
}
