{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1/util-test-1.8.1.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rru5f6r43jfulpvnho3ng475zy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1.jar",
          "url": "util-test-jvm-1.8.1.jar",
          "size": 5724,
          "sha512": "cb75e21978af116c7f1422b2f76fa5e96a01ff8f38e5802068f7b8179543f5199a007e8c7119d8995e4545f066eb38ca5e629c2ef540040143ca34b3594439e4",
          "sha256": "5168d1e46926d77441cf7beb67441c44b5642700437f96cad53ec03e40e80f49",
          "sha1": "bec6a7ab84ac54f65ace9fac0e8a6a859ad34ecf",
          "md5": "aaf9b309fc34302b38aad565738e2403"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1.jar",
          "url": "util-test-jvm-1.8.1.jar",
          "size": 5724,
          "sha512": "cb75e21978af116c7f1422b2f76fa5e96a01ff8f38e5802068f7b8179543f5199a007e8c7119d8995e4545f066eb38ca5e629c2ef540040143ca34b3594439e4",
          "sha256": "5168d1e46926d77441cf7beb67441c44b5642700437f96cad53ec03e40e80f49",
          "sha1": "bec6a7ab84ac54f65ace9fac0e8a6a859ad34ecf",
          "md5": "aaf9b309fc34302b38aad565738e2403"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1/util-test-metadata-1.8.1.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1"
      }
    }
  ]
}
