{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qt4l2o6jhbetfdszwongkjk6ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.14.0.jar",
          "url": "auth-jvm-1.14.0.jar",
          "size": 34319,
          "sha512": "6bc5bab6f31f77d8799f6fad9d8b1065e17b42e48ee743cd44a6bf7246f36217136360e2b024024dccdf3b8d725c145b11553c8bff7d55d2686c6768f1a92e8a",
          "sha256": "5a8fe6e1073404dc856f4b6ae6dd69e31002db1a5ba14fe7e028c02cf525e51b",
          "sha1": "0a0c9f6f509b3e30f45889ccca50f0e52badc62d",
          "md5": "904f8522318544ab9bcae73630eb3384"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.14.0.jar",
          "url": "auth-jvm-1.14.0.jar",
          "size": 34319,
          "sha512": "6bc5bab6f31f77d8799f6fad9d8b1065e17b42e48ee743cd44a6bf7246f36217136360e2b024024dccdf3b8d725c145b11553c8bff7d55d2686c6768f1a92e8a",
          "sha256": "5a8fe6e1073404dc856f4b6ae6dd69e31002db1a5ba14fe7e028c02cf525e51b",
          "sha1": "0a0c9f6f509b3e30f45889ccca50f0e52badc62d",
          "md5": "904f8522318544ab9bcae73630eb3384"
        }
      ]
    }
  ]
}
