{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.9.0.jar",
          "url": "fhir-helper-1.9.0.jar",
          "size": 1510,
          "sha512": "53a2e514c24c65529b1e22067fb8dac7e229105673f8a86b2633abaa319f72c4c5c1283d2180e4d0671bdf1fbcd5b1a9e1902506cd360d3b3ae9e56531f0f18f",
          "sha256": "1f4f220e14b5847a2c8d387a477eb2a13c34ad8bf078a19de136e9fd1973d59b",
          "sha1": "76d5f89afba0b2a6c513c2c2fa98418c4e292653",
          "md5": "876ab9af340d9acf107e8b16cecd5312"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.9.0/fhir-helper-android-debug-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.9.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.9.0/fhir-helper-android-debug-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.9.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.9.0/fhir-helper-android-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.9.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.9.0/fhir-helper-android-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.9.0/fhir-helper-jvm-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.9.0/fhir-helper-jvm-1.9.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.9.0"
      }
    }
  ]
}
