{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqumllzovzganehrscnruemkz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2.jar",
          "url": "crypto-common-1.13.2.jar",
          "size": 11519,
          "sha512": "e09c0255ed73788d22ecb6cca849f4350beda9f2ec0707292421c35d5e5e16ac2f258372a159d22a0ea3eb31f807ba452a0a62d113cfe242929b359cb9acc088",
          "sha256": "75f9da0817aa3ab1e063c77ea58f78ee7320e95e9a22934752bc663f02a098a0",
          "sha1": "84f3928b44974057bc28f68a6ed5873723b7cb7d",
          "md5": "d770e238ea82a3fcfcaa94991c548c3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2.jar",
          "url": "crypto-common-1.13.2.jar",
          "size": 11519,
          "sha512": "e09c0255ed73788d22ecb6cca849f4350beda9f2ec0707292421c35d5e5e16ac2f258372a159d22a0ea3eb31f807ba452a0a62d113cfe242929b359cb9acc088",
          "sha256": "75f9da0817aa3ab1e063c77ea58f78ee7320e95e9a22934752bc663f02a098a0",
          "sha1": "84f3928b44974057bc28f68a6ed5873723b7cb7d",
          "md5": "d770e238ea82a3fcfcaa94991c548c3c"
        }
      ]
    }
  ]
}
