{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0/util-1.13.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.13.0.klib",
          "size": 25786,
          "sha512": "0f56bce6a007735cb525e5ac8ee6e6775c85af3fba8004e2aac486ecbd1121d60be655c073f0bd4cc085ab4d105fc20705cfe9e0fa7657b595257a0aeec91293",
          "sha256": "6af17d22f5c4ca48e5a34db42b7259e7fdf0735626cc3cd38c93e37e4b27bc35",
          "sha1": "44dfd1995190e6b5ebcf74fa52007ab0fea1fded",
          "md5": "83e401a6d6b5ac26fe80907ad569c4ce"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.13.0-metadata.jar",
          "url": "util-iosarm64-1.13.0-metadata.jar",
          "size": 6109,
          "sha512": "b4e5d8e9489fd68c36a709acb43ee08b5dad70dd8c3e289e48d642d6f7031a87ededf8529379f13281b6e625986a88d877ac71a08cd5ad320c4621c4113aa1d9",
          "sha256": "c6d984b3cb6fba55b5bd9620e68a016f0143c26f88a1a7a3fd2c5ecafca206aa",
          "sha1": "6a1aa3da7691690328ca14c4721d74ca3c9f83d4",
          "md5": "a1af5d4265a072e6702437a0c62932d9"
        }
      ]
    }
  ]
}
