{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.14.0/crypto-1.14.0.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.14.0.jar",
          "url": "crypto-jvm-1.14.0.jar",
          "size": 59038,
          "sha512": "399c294dc5a2c56cc474272a390586628758c48421800573094b5d7de8fe2c0c86b6b0db27ab75faa0cd1465c8761b7a55f0e50425834c6ee339b7ba76d7db24",
          "sha256": "8daab9ef41c35b623f58d1e26169d80918117b8afdc816c0421e4d450ab50d3d",
          "sha1": "f228d615b7893ee034867737d0f7b0910a15a8fc",
          "md5": "67b3db192ba0584bd12f84482cd70188"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.14.0.jar",
          "url": "crypto-jvm-1.14.0.jar",
          "size": 59038,
          "sha512": "399c294dc5a2c56cc474272a390586628758c48421800573094b5d7de8fe2c0c86b6b0db27ab75faa0cd1465c8761b7a55f0e50425834c6ee339b7ba76d7db24",
          "sha256": "8daab9ef41c35b623f58d1e26169d80918117b8afdc816c0421e4d450ab50d3d",
          "sha1": "f228d615b7893ee034867737d0f7b0910a15a8fc",
          "md5": "67b3db192ba0584bd12f84482cd70188"
        }
      ]
    }
  ]
}
