{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.7.1/fhir-helper-1.7.1.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tfuef4o5sre3ddlb3cnxxincyq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1.jar",
          "url": "fhir-helper-jvm-1.7.1.jar",
          "size": 116366,
          "sha512": "c96c6fda9eaf856216b00e475f51969d4f05b2798842cbba2ddadbe33905604fec16db5353c9605243f13661ddb6c429e92f7a5921bcc681a2e907db00bdfd79",
          "sha256": "a255cf71010b5e9c9b8ba2372c69994eb1fd340e7a6c6d7d58a25978d23cd540",
          "sha1": "d1c89063c196a2410289031d74d034c8871d79fa",
          "md5": "e8fabae660266e144ad7fe1e1d2b336a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1.jar",
          "url": "fhir-helper-jvm-1.7.1.jar",
          "size": 116366,
          "sha512": "c96c6fda9eaf856216b00e475f51969d4f05b2798842cbba2ddadbe33905604fec16db5353c9605243f13661ddb6c429e92f7a5921bcc681a2e907db00bdfd79",
          "sha256": "a255cf71010b5e9c9b8ba2372c69994eb1fd340e7a6c6d7d58a25978d23cd540",
          "sha1": "d1c89063c196a2410289031d74d034c8871d79fa",
          "md5": "e8fabae660266e144ad7fe1e1d2b336a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.7.1/fhir-helper-metadata-1.7.1.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.7.1"
      }
    }
  ]
}
