{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.0/util-jvm-1.8.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "i4zniu7kpjbsfnynqhafozhlay"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.0.jar",
          "url": "util-metadata-1.8.0.jar",
          "size": 6309,
          "sha512": "f20b243b34aacc111a80d3cd1caa778f3b4cca0dc5703a49cb0fa8e2d859e709468956c60bc5cee0b607c59610d6993afaf965cc0dac40e42b14a08d05e926c3",
          "sha256": "f07fe8f057eb941da2161f9db86caf2ea1c4e57e6a79e8d76feebefade9ddaec",
          "sha1": "f91df4945d174317b1c4a4adcce3110206b29efe",
          "md5": "e04b642676af2138aecda046e4bcb7e4"
        }
      ]
    }
  ]
}
