{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1.jar",
          "url": "crypto-jvm-1.13.1.jar",
          "size": 57138,
          "sha512": "d562b89bc5f348ede2a34afa8dff5db74e900f47d82114ac1cc9091d36010758d0086d50bd351ce2120ba959c7b2a0a34531e855c12d547660926b1e7400dbd5",
          "sha256": "89507620bc54e1a4445864eb30262384e7587e2a6c0383d2b70e5a0562ad980e",
          "sha1": "76e17b8f1683bc50fcb92146c008b28a636c122c",
          "md5": "1a5bc547a015c3f311dd70533cdd4b97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1.jar",
          "url": "crypto-jvm-1.13.1.jar",
          "size": 57138,
          "sha512": "d562b89bc5f348ede2a34afa8dff5db74e900f47d82114ac1cc9091d36010758d0086d50bd351ce2120ba959c7b2a0a34531e855c12d547660926b1e7400dbd5",
          "sha256": "89507620bc54e1a4445864eb30262384e7587e2a6c0383d2b70e5a0562ad980e",
          "sha1": "76e17b8f1683bc50fcb92146c008b28a636c122c",
          "md5": "1a5bc547a015c3f311dd70533cdd4b97"
        }
      ]
    }
  ]
}
