{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2/data-donation-sdk-iosx64-0.1.2.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lxxxd5lqwzfd3ojqoqjk3rrxdi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2.jar",
          "url": "data-donation-sdk-metadata-0.1.2.jar",
          "size": 39147,
          "sha512": "72f520de966a9c74d2b353f64890e900425144a977b35ed932eff49add75bcef3bece3771828ad5d74894b20666d6309c391f8f015a9951becd662c5e9cd3ff6",
          "sha256": "e70dc99246b6f8a4a1dfacdf35cbb0aca5143071740b236c9dd8dbfe93a7f7e8",
          "sha1": "530249d66087cd9978fb90a6c6128f8934fb956d",
          "md5": "ea12eab965729ba7cfea819e19bb4a99"
        }
      ]
    }
  ]
}
