{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0/test-util-0.3.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosx64-0.3.0.klib",
          "size": 16547,
          "sha512": "870f6b75858a03ff6018bf8853e1dc51cc233eb83ea08685fa1f7223a4912284d428f298a2f9630a3876144998e9b9e0c3dc372bd74b3f26372c64f2b1d394d0",
          "sha256": "8cf6e80ade2a989011b7fade1741bed3c87a71f4da3b33e307e8d0ed05d4bbb9",
          "sha1": "ed45a07edfc97472aa6084688124c51834e4a0af",
          "md5": "f17cafe1105d24a0068184826d3e8fdb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosx64-0.3.0-metadata.jar",
          "url": "test-util-iosx64-0.3.0-metadata.jar",
          "size": 7055,
          "sha512": "9e1acbf41e48693897196c32bb6fce81a5fa1632fc7c76b9128aff3bd67acc4dfbc32caf766d4707ef7fdd8bf85cde8c7d127d895fcc143893a586f60b78efeb",
          "sha256": "aa67e2cad928a8d942d0a6c6a654799ebd7a4a3778f42a7d7cfc7b0b218725f0",
          "sha1": "f66828747c77d40dd29f8df7f0c0c4baf2d0fd78",
          "md5": "51a0519b2a072da7486602fbdaa8df45"
        }
      ]
    }
  ]
}
