{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.12.0/util-1.12.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.12.0.klib",
          "size": 25769,
          "sha512": "41694487c662f68d2ed6a1d05af4973f225a3d1bf191ef4e78fcb71323d56bfd819fca2b0e78dde008b351ea4e7f5419a11ef550556fa4d202de72727f9e050b",
          "sha256": "cf81e7166b7e7d242eab202bc8b943e2d2b1a975df14932a76afeaf5fe33ebdc",
          "sha1": "5b18856e53efe56b9d849ae0b14e6a85acd91a0e",
          "md5": "be5e0e80abd1e6eab87535cb6e14d8e9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.12.0-metadata.jar",
          "url": "util-iosx64-1.12.0-metadata.jar",
          "size": 6109,
          "sha512": "c200e6370e1a6d449ce1129b5e8d80f757b8016f978fbd7017ec4a976935a4cdb54abd4f5fa3393eebe97cfa45098445d954258a96c2848313cd2722eb3e8544",
          "sha256": "09873061d9f892d5cd5515fe1980a09c9f42ea34a551270e9d6dd02c6ec0dfba",
          "sha1": "c3efc615c1851346c89fecc58495f98e0cfcc853",
          "md5": "6e0f443652e5993bfd33421083c87eb2"
        }
      ]
    }
  ]
}
