{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0/util-ktor-test-1.9.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aitrtwsoyvbztl5swknjdi3ioi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0.jar",
          "url": "util-ktor-test-jvm-1.9.0.jar",
          "size": 28641,
          "sha512": "8a97800219fc722807d13b49ee08f17563c2074f0a02788d888d4a4e8c96931aacc49b79e7b433e16b0ea6f1da7d21d2938246bd17eae3a9c0b6029cfe0d1f08",
          "sha256": "9a37b512c4ecbd578e6a1dfff2ef9d7dfda882f92932fcbdacc2c672c3730ef7",
          "sha1": "80f5ea306acac7e4d32b5896c91d4c599a550933",
          "md5": "43aab7f236ac2d5f1fb2b698e1a7de5a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0.jar",
          "url": "util-ktor-test-jvm-1.9.0.jar",
          "size": 28641,
          "sha512": "8a97800219fc722807d13b49ee08f17563c2074f0a02788d888d4a4e8c96931aacc49b79e7b433e16b0ea6f1da7d21d2938246bd17eae3a9c0b6029cfe0d1f08",
          "sha256": "9a37b512c4ecbd578e6a1dfff2ef9d7dfda882f92932fcbdacc2c672c3730ef7",
          "sha1": "80f5ea306acac7e4d32b5896c91d4c599a550933",
          "md5": "43aab7f236ac2d5f1fb2b698e1a7de5a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0/util-ktor-test-metadata-1.9.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0"
      }
    }
  ]
}
