{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lvk6ajwewfdoho33we7nbsfcci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1.jar",
          "url": "auth-common-1.13.1.jar",
          "size": 3578,
          "sha512": "e7ba54c9b3ac29d7664bd9fe3fed3b3cf822b677354ba324a48dad1a736f00cd2f700f86a1fb4d8949345c7f14ab86a1132585212145a885e178717014d1a040",
          "sha256": "1e081ea41ff6067649a25a148eb9b8e48cf1dedea50cbcd9f342f05d64af8fea",
          "sha1": "d6ae05a294219c76895f01291369b760766a9f0d",
          "md5": "7583e758369a582c672528b42cb67f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1.jar",
          "url": "auth-common-1.13.1.jar",
          "size": 3578,
          "sha512": "e7ba54c9b3ac29d7664bd9fe3fed3b3cf822b677354ba324a48dad1a736f00cd2f700f86a1fb4d8949345c7f14ab86a1132585212145a885e178717014d1a040",
          "sha256": "1e081ea41ff6067649a25a148eb9b8e48cf1dedea50cbcd9f342f05d64af8fea",
          "sha1": "d6ae05a294219c76895f01291369b760766a9f0d",
          "md5": "7583e758369a582c672528b42cb67f11"
        }
      ]
    }
  ]
}
