{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7jqgdhmx6bhxdfbmessygnjnem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0.jar",
          "url": "crypto-common-1.12.0.jar",
          "size": 11519,
          "sha512": "39b7c2b072fb8ae67ebe2efe8ca3784dc5e842a42e6236ac6ebfb31a6ff401fe43dcd660c5f9a1e94692053a7063ad9c3e59a8a7e78f18aab0fe650da3db226b",
          "sha256": "816b68cb62afeef3b662cbe238465bcb201205ac85a6167a582e145dd4e2235e",
          "sha1": "d79adf6696fb7613c6fdd14090608150f555f3ab",
          "md5": "647ab50b72c0fb5e3862214c88c2baa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0.jar",
          "url": "crypto-common-1.12.0.jar",
          "size": 11519,
          "sha512": "39b7c2b072fb8ae67ebe2efe8ca3784dc5e842a42e6236ac6ebfb31a6ff401fe43dcd660c5f9a1e94692053a7063ad9c3e59a8a7e78f18aab0fe650da3db226b",
          "sha256": "816b68cb62afeef3b662cbe238465bcb201205ac85a6167a582e145dd4e2235e",
          "sha1": "d79adf6696fb7613c6fdd14090608150f555f3ab",
          "md5": "647ab50b72c0fb5e3862214c88c2baa5"
        }
      ]
    }
  ]
}
