{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.5.0/test-util-ktor-0.5.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.5.0.klib",
          "size": 15755,
          "sha512": "880d4cae6db0c73abca2ca2b38a7ba33a96d508adf205c8394e575fe0f7bd942cb4bdd4b573095778575f3c293b8a3d6f9facd4bf899e2f4fef48294ab20d31f",
          "sha256": "3b0f9dd9a65f38ed7f262eb03ec1a5af57d6abffdd5a9e871cbe4d3a284f07c0",
          "sha1": "00cd4a5ba77d94690846a40e9aa0deafb1fed1c5",
          "md5": "37037efa20d56d7bf04d7d5d2d16eebb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.5.0-metadata.jar",
          "url": "test-util-ktor-iosx64-0.5.0-metadata.jar",
          "size": 261,
          "sha512": "549b8b969afeaf72b5c03f7f8dbda4e0607ddc5c796f0df0227768107f7c693b218732b6e536844ffc7fd2e59b107627accb45cfdddfef00b45072d052b96997",
          "sha256": "82aa979ec53c622da41add073503116b610b93a22b113332f534ff82e60b2c31",
          "sha1": "d4b7a5fa6b8285e3e687b375423809320d7d53d4",
          "md5": "954a6346af7fa7d140d4796e209a91e7"
        }
      ]
    }
  ]
}
