{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0/data-donation-sdk-iosx64-0.1.0.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mfpdyfv2aze6tpev4gam5oydfi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0.jar",
          "url": "data-donation-sdk-metadata-0.1.0.jar",
          "size": 40185,
          "sha512": "4ca51d5e7f1bf20bfdc2b4212e2a194bc832985c2541a39c77d7602c59cdc24c11a8a1f8da4a10ea1f336f0206b34240b4d255a5c0d91760b80a978bf9663391",
          "sha256": "5587ce0fe7f548ed9d79b55871b26adcb497406683e5414a0ee821c769f044a8",
          "sha1": "44910135bb44f647827b32b518d323de0cb5b3c6",
          "md5": "65d597bd0019692a37e16e16f0353efa"
        }
      ]
    }
  ]
}
