{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0/test-util-ktor-0.3.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.3.0.klib",
          "size": 15005,
          "sha512": "4b5cfe5d52c304e429c0af886859d33d13ab5a8b50bfa5921c2e9d92a3b353612cfa2d411606c949f7e82fa3eb1bea05d720b1179cb296ca3615b3ff1062ca66",
          "sha256": "507585872a0c1411c255a7c77a9dc38ac1625144f52a284e87511baa71faecfd",
          "sha1": "e4dcd4d54d7ef9dd4717f8b88dc20c18cc65c321",
          "md5": "b345758e1955e374cb891010e338cff0"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.3.0-metadata.jar",
          "url": "test-util-ktor-iosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "687bf0e1ec99e6f07cf6ab6e9688a84b7df33ea9b3eed0ddab376bddac507dc6c3bb02f95ec13f1a35637016eb2fdaa387f57a138cfd8baa30f167906d9c31d7",
          "sha256": "26495353a767c3e36be9738c697c8def0e27108ae315396bcb2e39a02c67ddf7",
          "sha1": "402df6f27e33bb39da9c246101d4728926648fee",
          "md5": "38d72b29991188f2cdc9f6eb0c1c730a"
        }
      ]
    }
  ]
}
