{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-metadata-1.12.0-all.jar",
          "url": "error-1.12.0-all.jar",
          "size": 3914,
          "sha512": "81c7caf70b652d4b4df81acf5bd1757ff1efd824fc95d8bcf00b633d8ec55d2655e06251b0e7b79e9ebb9f473c182a9affbefbc72aee940619492a809161b1f0",
          "sha256": "c11318a062644479768ff3eb3ae761340374986bcd03c813d7c8d2c9aa769950",
          "sha1": "064010395e2c9e48da77bdaac203bc0ca784a796",
          "md5": "d6ab6af6920b60bbcc9de85248ed5682"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "error-1.12.0.jar",
          "url": "error-1.12.0.jar",
          "size": 1921,
          "sha512": "5ae51a3a55b6c12b06f5a3b3cbc18bd588c12f83ccdfc6b99089d0c29e8f95a9560a340c0acb6b41bbdb813585f333d51c9b05137ebd780dd9f94112ed5f6ebf",
          "sha256": "83add30d971ef8436da1bfbe645f351d8e7f0ebb6003cd2255301b6d61282311",
          "sha1": "7730f39df6fb2dfebae2075484e644879d03cff2",
          "md5": "8d0ea3c5645fb789c4340e2415b7f9be"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android-debug/1.12.0/error-android-debug-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android-debug",
        "version": "1.12.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android-debug/1.12.0/error-android-debug-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android-debug",
        "version": "1.12.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android/1.12.0/error-android-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android",
        "version": "1.12.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../error-android/1.12.0/error-android-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-android",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosarm64/1.12.0/error-iosarm64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosarm64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosarm64/1.12.0/error-iosarm64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosarm64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosx64/1.12.0/error-iosx64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosx64",
        "version": "1.12.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../error-iosx64/1.12.0/error-iosx64-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-iosx64",
        "version": "1.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../error-jvm/1.12.0/error-jvm-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-jvm",
        "version": "1.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../error-jvm/1.12.0/error-jvm-1.12.0.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "error-jvm",
        "version": "1.12.0"
      }
    }
  ]
}
