{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqumllzovzganehrscnruemkz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 57138,
          "sha512": "82ee8d8de3c08fa418fc33e4e84c01579a349d04d66304b22d762a09ab62a1f77ee1fda57ef6ff5514be9d38ca80306b15b525b04ad69bca6fb1d9b96af16b73",
          "sha256": "c83d526bd6783b11035607417908b16b12e1845be04de83ac2bf1b718525ebe0",
          "sha1": "9e7ff7dd7a03787b36b08889c0f41b0a6a6bef43",
          "md5": "a74a14a69f72297b7473a3af809caa8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 57138,
          "sha512": "82ee8d8de3c08fa418fc33e4e84c01579a349d04d66304b22d762a09ab62a1f77ee1fda57ef6ff5514be9d38ca80306b15b525b04ad69bca6fb1d9b96af16b73",
          "sha256": "c83d526bd6783b11035607417908b16b12e1845be04de83ac2bf1b718525ebe0",
          "sha1": "9e7ff7dd7a03787b36b08889c0f41b0a6a6bef43",
          "md5": "a74a14a69f72297b7473a3af809caa8d"
        }
      ]
    }
  ]
}
