{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.7.0/fhir-helper-1.7.0.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "rm7xkzwauvhp7js5z3bvdxpb4a"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.0.jar",
          "url": "fhir-helper-jvm-1.7.0.jar",
          "size": 116366,
          "sha512": "05d4cbec615a2c9a77ff9181efa8b7f403f8d0a5df1c49f07d98eae48cff26ddc96196524be2d457e943fb9a066710411a2212d8d9aa22d1eaed0acb7df7f86f",
          "sha256": "397be039cba50dc03c67ad2ae09d2afe72deb249236cb601a27fcc81a4d61db5",
          "sha1": "bc51688d19e4f84dbc4816e51461eaf037d68698",
          "md5": "839f4101388627014454392d97a3793f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.0.jar",
          "url": "fhir-helper-jvm-1.7.0.jar",
          "size": 116366,
          "sha512": "05d4cbec615a2c9a77ff9181efa8b7f403f8d0a5df1c49f07d98eae48cff26ddc96196524be2d457e943fb9a066710411a2212d8d9aa22d1eaed0acb7df7f86f",
          "sha256": "397be039cba50dc03c67ad2ae09d2afe72deb249236cb601a27fcc81a4d61db5",
          "sha1": "bc51688d19e4f84dbc4816e51461eaf037d68698",
          "md5": "839f4101388627014454392d97a3793f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.7.0/fhir-helper-metadata-1.7.0.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.7.0"
      }
    }
  ]
}
