{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.14.0/util-1.14.0.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.14.0.klib",
          "size": 25777,
          "sha512": "16cb6b3d4c0358d1c86af62f9c60b2aa8e5f06115b0269395bb932d02ae20aae773446fd74029b166c704c5c08cb6e717e66c65671e2817c54b15e0d5c22bc2d",
          "sha256": "7fcad917d96aac0a9d0c3628ba1bbf05e52dd4848cb8117c6a094cc8adb32c19",
          "sha1": "a7c0e9f653edf1accf9f72b0b91d74bc883304d9",
          "md5": "5bc051454ae306770f82ccf14ccb765d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.14.0-metadata.jar",
          "url": "util-iosx64-1.14.0-metadata.jar",
          "size": 6142,
          "sha512": "2de1572397ec6ad58d9f9067602d419e0f56a64ce9492bde50b2fc2ed976acb990dbbe052397877660b0e85f34009566ba7707d9eaf5a3ba41361167673ec864",
          "sha256": "f903beb9ed02b398b5077e754bb4f8797f002889f20f83f7f14cce5bb183f607",
          "sha1": "3ec013fc03935fabab66bf11d45eb89914ed636b",
          "md5": "4fe7afee95b947f21080877da5be087b"
        }
      ]
    }
  ]
}
