{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.1.0/test-util-ktor-0.1.0.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "acivhj2lyrg6hfvetor6vh3due"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0.jar",
          "url": "test-util-ktor-jvm-0.1.0.jar",
          "size": 28646,
          "sha512": "02a691232857949a9cf65129ac4c149f66262d9c7e4ee06af6a35bc8392fe2efa6f3fabf098910f978f7156777e4c518400d216261c904f865dba1247466a76a",
          "sha256": "d14ca701b4c3b7912ec13df45fc37c99400a9edd41dd91a1a04d2fe3cc292c32",
          "sha1": "1fd7bd0a6488c2766b154409d80f913a61a03b64",
          "md5": "e008a482b59b6f3514714a20ce7a8a18"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0.jar",
          "url": "test-util-ktor-jvm-0.1.0.jar",
          "size": 28646,
          "sha512": "02a691232857949a9cf65129ac4c149f66262d9c7e4ee06af6a35bc8392fe2efa6f3fabf098910f978f7156777e4c518400d216261c904f865dba1247466a76a",
          "sha256": "d14ca701b4c3b7912ec13df45fc37c99400a9edd41dd91a1a04d2fe3cc292c32",
          "sha1": "1fd7bd0a6488c2766b154409d80f913a61a03b64",
          "md5": "e008a482b59b6f3514714a20ce7a8a18"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.1.0/test-util-ktor-metadata-0.1.0.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.1.0"
      }
    }
  ]
}
